// <auto-generated>
// Generated by `ssisx generate` -- a STARTER unit test proving 'DFT_Load' genuinely
// reads, transforms, and writes at least one row end to end -- reconstructs a fresh
// DataFlowStep from the same source/transform/sink pieces the real package uses (never
// calls the generated step method directly -- see this file's own doc comment for why:
// a private _load field only RunAsync() populates). Regenerating this file freely
// discards any hand edits.
// </auto-generated>
#nullable enable
using System;
using Etl.Core.Abstractions;
using Etl.Core.Pipeline;
using Microsoft.Extensions.Logging.Abstractions;
using SyntheticScriptComponentSeams.Sql;
using SyntheticScriptComponentSeams.Model;
using SyntheticScriptComponentSeams.Mapping;
using SyntheticScriptComponentSeams.TestDoubles;
using Xunit;

namespace SyntheticScriptComponentSeams.Tests;

public class DFT_LoadStepDataFlowTests
{
    [Fact]
    [Trait("Category", "Integration")]
    public async Task DFT_Load_WritesAtLeastOneRow_EndToEnd()
    {
        using var harness = new PackageHarness();
        var package = harness.Package();
        var uow = harness.NewUnitOfWork();

        var source = package.OLEDBSource(uow);
        var transform = new SyntheticScriptSeamsTargetTransform();
        var sink = package.OLEDBDestination();
        var step = new DataFlowStep<SyntheticScriptSeamsTargetSqlRow, SyntheticScriptSeamsTarget>("DFT_Load", source, transform, sink, NullLogger<DataFlowStep<SyntheticScriptSeamsTargetSqlRow, SyntheticScriptSeamsTarget>>.Instance);

        await step.RunAsync(uow, new LoadContext(Guid.NewGuid(), DateTime.UtcNow, "DFT_Load"), CancellationToken.None);

        Assert.NotEmpty(uow.BulkInserts);
    }
}
