// <auto-generated>
// Generated by `ssisx generate` -- a STARTER unit test for OLEDBSource(), proving
// it constructs correctly and reports its own Name -- SqlRowSource<TRow>'s own
// constructor never opens a connection, so this needs no real database. A second,
// [Trait("Category", "Integration")]-tagged test attempts a real read; it needs whatever
// server this environment's own configuration resolves and is skipped by `dotnet test
// --filter Category!=Integration`. Regenerating this file freely discards any hand edits
// -- move those into a second file instead.
// </auto-generated>
#nullable enable
using SyntheticScriptComponentSeams.Sql;
using SyntheticScriptComponentSeams.TestDoubles;
using Xunit;

namespace SyntheticScriptComponentSeams.Tests;

public class OLEDBSourceSourceTests
{
    [Fact]
    public void OLEDBSource_ReportsItsOwnName()
    {
        using var harness = new PackageHarness();
        var package = harness.Package();
        var uow = harness.NewUnitOfWork();

        var source = package.OLEDBSource(uow);

        Assert.Equal("OLE DB Source", source.Name);
    }

    [Fact]
    [Trait("Category", "Integration")]
    public async Task OLEDBSource_ReadsRealRows_AgainstARealServer()
    {
        using var harness = new PackageHarness();
        var package = harness.Package();
        await using var uow = await harness.NewRealUnitOfWorkAsync();
        var source = package.OLEDBSource(uow);

        var rows = new List<SyntheticScriptSeamsTargetSqlRow>();
        await foreach (var row in source.ReadAsync(CancellationToken.None)) rows.Add(row);

        Assert.NotNull(rows);
    }
}
