// <auto-generated>
// Generated by `ssisx generate` -- a STARTER unit test for OLEDBDestination(), proving it
// writes every synthesized row through IUnitOfWork with no real database involved.
// Regenerating this file freely discards any hand edits -- move those into a second file
// instead.
// </auto-generated>
#nullable enable
using SyntheticScriptComponentSeams.Model;
using SyntheticScriptComponentSeams.TestDoubles;
using Xunit;

namespace SyntheticScriptComponentSeams.Tests;

public class SyntheticScriptSeamsTargetSinkTests
{
    [Fact]
    public async Task WriteAsync_WritesEveryRow_ThroughTheUnitOfWork()
    {
        using var harness = new PackageHarness();
        var uow = harness.NewUnitOfWork();
        var package = harness.Package();
        var sink = package.OLEDBDestination();

        var rows = new[]
        {
            new SyntheticScriptSeamsTarget { ID = 7, FirstName = "Sample", LastName = "Sample", FullName = "Sample", IsValid = true },
            new SyntheticScriptSeamsTarget { ID = 7, FirstName = "Sample", LastName = "Sample", FullName = "Sample", IsValid = true },
        };

        var written = await sink.WriteAsync(uow, ToAsyncEnumerable(rows), CancellationToken.None);

        Assert.Equal(2, written);
        var call = Assert.Single(uow.BulkInserts);
        Assert.Equal(2, call.RowsWritten);
        Assert.Equal(5, call.ColumnMappings.Count);
        Assert.False(string.IsNullOrWhiteSpace(call.DestinationTable));
    }

    private static async IAsyncEnumerable<SyntheticScriptSeamsTarget> ToAsyncEnumerable(IEnumerable<SyntheticScriptSeamsTarget> items)
    {
        foreach (var item in items) yield return item;
        await Task.CompletedTask;
    }
}
