using Ssis.Extract.Dtsx;
using Ssis.Extract.Model.Pipeline;

namespace Ssis.Extract.Codegen;

/// <summary>
/// Per-component starter tests beyond what <see cref="SqlStatementTestEmitter"/> (Execute SQL) and
/// <see cref="TransformTestEmitter"/> (a flow's own Map()) already cover -- phase 2 of the
/// generated-tests plan (<c>Docs/Generated-Tests-Plan.md</c>).
///
/// Starts with exactly one taxonomy row: "Sink -- SQL". It reuses
/// <see cref="PipelineResolver.ResolveDestinationInput"/> for the EXACT same column set
/// <c>EntityEmitter</c> itself builds `{Entity}.cs`'s own properties from, and
/// <see cref="TransformTestEmitter.RepresentativeLiteral"/> for the exact same representative
/// values every other starter test in this tool already uses -- so a synthesized row here can
/// never disagree with what the generated entity/sink actually declare.
/// </summary>
public static class ComponentTestEmitter
{
    public static EmitResult EmitSqlSinkTest(
        string testNamespace,
        string rootNamespace,
        string entityNamespace,
        string entityName,
        string sinkMethodName,
        PipelineComponentSpec destinationComponent)
    {
        var resolved = PipelineResolver.ResolveDestinationInput(destinationComponent);
        // Independently reproduces EntityEmitter's own identifier mapping (same
        // PipelineResolver.ResolveDestinationInput list, same order) -- see
        // PackageGenerator.MakeColumnIdentifierResolver's own doc comment.
        var identifierOf = PackageGenerator.MakeColumnIdentifierResolver();
        var propertyInits = new List<string>();
        foreach (var column in resolved.Columns)
        {
            // A column with no resolvable CLR type is already reported elsewhere (EntityEmitter's
            // own gap for it) -- this starter test just leaves it unset rather than repeating that
            // gap a second time.
            if (column.Type is not { } clrType) continue;
            propertyInits.Add($"{identifierOf(column.ExternalColumnName)} = {TransformTestEmitter.RepresentativeLiteral(clrType.ClrTypeName)}");
        }

        // Nothing this pilot can synthesize a value for -- no starter test, and no gap either
        // (every column that could not resolve already has its own gap from EntityEmitter/
        // TransformEmitter; this is genuinely out of scope, not something new to report).
        if (propertyInits.Count == 0) return new EmitResult([], []);

        var initializer = string.Join(", ", propertyInits);

        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {sinkMethodName}(), proving it",
            "// writes every synthesized row through IUnitOfWork with no real database involved.",
            "// Regenerating this file freely discards any hand edits -- move those into a second file",
            "// instead.",
            "// </auto-generated>",
            "#nullable enable",
            $"using {entityNamespace};",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {entityName}SinkTests",
            "{",
            "    [Fact]",
            "    public async Task WriteAsync_WritesEveryRow_ThroughTheUnitOfWork()",
            "    {",
            "        using var harness = new PackageHarness();",
            "        var uow = harness.NewUnitOfWork();",
            "        var package = harness.Package();",
            $"        var sink = package.{sinkMethodName}();",
            "",
            "        var rows = new[]",
            "        {",
            $"            new {entityName} {{ {initializer} }},",
            $"            new {entityName} {{ {initializer} }},",
            "        };",
            "",
            "        var written = await sink.WriteAsync(uow, ToAsyncEnumerable(rows), CancellationToken.None);",
            "",
            "        Assert.Equal(2, written);",
            "        var call = Assert.Single(uow.BulkInserts);",
            "        Assert.Equal(2, call.RowsWritten);",
            $"        Assert.Equal({propertyInits.Count}, call.ColumnMappings.Count);",
            "        Assert.False(string.IsNullOrWhiteSpace(call.DestinationTable));",
            "    }",
            "",
            $"    private static async IAsyncEnumerable<{entityName}> ToAsyncEnumerable(IEnumerable<{entityName}> items)",
            "    {",
            "        foreach (var item in items) yield return item;",
            "        await Task.CompletedTask;",
            "    }",
            "}",
        };

        return new EmitResult([new GeneratedFile($"{entityName}SinkTests.cs", Rendering.JoinLines(lines))], []);
    }

    /// <summary>"Sink -- flat file" taxonomy row. Unlike <see cref="EmitSqlSinkTest"/>,
    /// <c>FlatFileBulkSink&lt;TEntity&gt;</c> never touches <c>IUnitOfWork</c> at all (see that
    /// type's own doc comment) -- there is nothing to fake, so this writes to a real, isolated
    /// per-instance temp file (<c>harness.SinkFilePath</c>/the same <c>FileSourceOptions</c> key
    /// <c>PackageHarness</c> wires up for it) and reads the ACTUAL bytes back, rather than
    /// re-implementing <c>FlatFileBulkSink</c>'s own delimiter/fixed-width/header formatting logic
    /// a second time here (which would only ever prove the two copies agree with each other, not
    /// that either is right). Asserts row/line count and non-emptiness -- exact byte content is
    /// what the dtexec-comparison fixtures already prove.</summary>
    public static EmitResult EmitFlatFileSinkTest(
        string testNamespace,
        string rootNamespace,
        string entityNamespace,
        string entityName,
        string sinkMethodName,
        string fileSourceKey,
        bool hasHeader,
        string rowTerminator,
        PipelineComponentSpec destinationComponent)
    {
        var resolved = PipelineResolver.ResolveDestinationInput(destinationComponent);
        // Independently reproduces EntityEmitter's own identifier mapping -- see
        // PackageGenerator.MakeColumnIdentifierResolver's own doc comment.
        var identifierOf = PackageGenerator.MakeColumnIdentifierResolver();
        var propertyInits = new List<string>();
        foreach (var column in resolved.Columns)
        {
            if (column.Type is not { } clrType) continue;
            propertyInits.Add($"{identifierOf(column.ExternalColumnName)} = {TransformTestEmitter.RepresentativeLiteral(clrType.ClrTypeName)}");
        }

        if (propertyInits.Count == 0) return new EmitResult([], []);

        var initializer = string.Join(", ", propertyInits);
        var expectedLines = hasHeader ? 3 : 2; // header (if any) + 2 synthesized rows

        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {sinkMethodName}(), proving it",
            "// writes every synthesized row to a real file (FlatFileBulkSink never touches",
            "// IUnitOfWork -- see its own doc comment) and reading the actual written bytes back, with",
            "// no real database involved. Regenerating this file freely discards any hand edits -- move",
            "// those into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
            $"using {entityNamespace};",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {entityName}SinkTests",
            "{",
            "    [Fact]",
            "    public async Task WriteAsync_WritesEveryRow_ToARealFile()",
            "    {",
            "        using var harness = new PackageHarness();",
            "        var uow = harness.NewUnitOfWork();",
            "        var package = harness.Package();",
            $"        var sink = package.{sinkMethodName}();",
            "",
            "        var rows = new[]",
            "        {",
            $"            new {entityName} {{ {initializer} }},",
            $"            new {entityName} {{ {initializer} }},",
            "        };",
            "",
            "        var written = await sink.WriteAsync(uow, ToAsyncEnumerable(rows), CancellationToken.None);",
            "",
            "        Assert.Equal(2, written);",
            $"        var filePath = harness.SinkFilePath({ProgramEmitter.CSharpStringLiteral(fileSourceKey)});",
            "        Assert.True(File.Exists(filePath));",
            "        var text = await File.ReadAllTextAsync(filePath);",
            "        Assert.False(string.IsNullOrWhiteSpace(text));",
        };

        // The row/line terminator is whatever the destination's own last physical column's
        // delimiter decodes to (FlatFileBulkSink/ResolveFlatFileSink both build header and data
        // rows the same way -- see that method's own doc comment) -- splitting on it directly
        // rather than assuming "\r\n" universally, and skipping the count assertion entirely on
        // the one case (an empty terminator) where a line count is not a meaningful concept.
        if (!string.IsNullOrEmpty(rowTerminator))
            lines.Add($"        Assert.Equal({expectedLines}, text.Split({ProgramEmitter.CSharpStringLiteral(rowTerminator)}, StringSplitOptions.RemoveEmptyEntries).Length);");

        lines.Add("    }");
        lines.AddRange(new List<string>
        {
            "",
            $"    private static async IAsyncEnumerable<{entityName}> ToAsyncEnumerable(IEnumerable<{entityName}> items)",
            "    {",
            "        foreach (var item in items) yield return item;",
            "        await Task.CompletedTask;",
            "    }",
            "}",
        });

        return new EmitResult([new GeneratedFile($"{entityName}SinkTests.cs", Rendering.JoinLines(lines))], []);
    }

    /// <summary>"Source -- CSV/fixed-width" (and, since Phase 5 of the unsupported-component-types
    /// plan, XML) taxonomy row: <c>Docs/Generated-Tests-Plan.md</c>'s own wording is "assert .Name;
    /// full read tagged" -- the same shape <see cref="EmitSqlSourceTest"/>/<see cref="EmitExcelSourceTest"/>
    /// already use, not the row-count/column assertions an earlier version of this test made against
    /// a tool-synthesized Tier-A sample. That Tier-A fallback is gone (2026-09-06): every file-based
    /// source, this one included, now resolves through the SAME package-relative <c>TestData/</c>
    /// folder <c>appsettings.Development.json</c> already points a real local run at -- see
    /// <see cref="TestDoublesEmitter"/>'s own doc comment -- so a real read needs its own
    /// <c>LOCAL-DATA</c> fill applied first, exactly like a SQL source needs a real server and an
    /// Excel source needs a real workbook. <c>CsvRowSource&lt;TRow&gt;</c>/
    /// <c>FixedWidthRowSource&lt;TRow&gt;</c>/<c>XmlRowSource&lt;TRow&gt;</c>'s own constructors never
    /// open the file (lazy, like <c>SqlRowSource&lt;TRow&gt;</c>, unlike
    /// <c>ExcelRowSource&lt;TRow&gt;</c>'s eager one), so the <c>.Name</c>-only test needs no
    /// registered file at all, only a registered DICTIONARY ENTRY (still supplied unconditionally by
    /// <see cref="TestDoublesEmitter"/>, so no <c>KeyNotFoundException</c> either way).</summary>
    public static GeneratedFile EmitFileSourceTest(
        string testNamespace, string rootNamespace, string rowTypeNamespace, string rowTypeName,
        string sourceMethodName, bool sourceNeedsUow, string componentName)
    {
        var nameLiteral = ProgramEmitter.CSharpStringLiteral(componentName);
        var uowArg = sourceNeedsUow ? "uow" : "";
        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {sourceMethodName}(), proving",
            "// it constructs correctly and reports its own Name -- this row source's own constructor",
            "// (CsvRowSource<TRow>/FixedWidthRowSource<TRow>/XmlRowSource<TRow>) never opens its file",
            "// at construction, so this needs no real file. A",
            "// second, [Trait(\"Category\", \"Integration\")]-tagged test attempts a real read; it needs a",
            "// real file under TestData/ matching this source's own configured name (see the LOCAL-DATA",
            "// work packet) and is skipped by `dotnet test --filter Category!=Integration`. Regenerating",
            "// this file freely discards any hand edits -- move those into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
            $"using {rowTypeNamespace};",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {sourceMethodName}SourceTests",
            "{",
            "    [Fact]",
            $"    public void {sourceMethodName}_ReportsItsOwnName()",
            "    {",
            "        using var harness = new PackageHarness();",
            "        var package = harness.Package();",
        };
        if (sourceNeedsUow) lines.Add("        var uow = harness.NewUnitOfWork();");
        lines.Add($"        var source = package.{sourceMethodName}({uowArg});");
        lines.Add("");
        lines.Add($"        Assert.Equal({nameLiteral}, source.Name);");
        lines.Add("    }");
        lines.Add("");
        lines.Add("    [Fact]");
        lines.Add("    [Trait(\"Category\", \"Integration\")]");
        lines.Add($"    public async Task {sourceMethodName}_ReadsRealRows_AgainstARealFile()");
        lines.Add("    {");
        lines.Add("        using var harness = new PackageHarness();");
        lines.Add("        var package = harness.Package();");
        if (sourceNeedsUow) lines.Add("        var uow = harness.NewUnitOfWork();");
        lines.Add($"        var source = package.{sourceMethodName}({uowArg});");
        lines.Add("");
        lines.Add($"        var rows = new List<{rowTypeName}>();");
        lines.Add("        await foreach (var row in source.ReadAsync(CancellationToken.None)) rows.Add(row);");
        lines.Add("");
        lines.Add("        Assert.NotNull(rows);");
        lines.Add("    }");
        lines.Add("}");

        return new GeneratedFile($"{sourceMethodName}SourceTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>"Source -- SQL" taxonomy row: <c>Docs/Generated-Tests-Plan.md</c>'s own wording is
    /// "assert .Name; full read tagged". <c>SqlRowSource&lt;TRow&gt;</c>'s own constructor never
    /// opens a connection (plain field assignment -- confirmed by reading it directly, same as
    /// every other bypass in this file), so constructing it and asserting its own <c>Name</c>
    /// needs no real server at all; only enumerating <c>ReadAsync</c> does, so that assertion is
    /// its own separate, <c>[Trait("Category", "Integration")]</c>-tagged <c>[Fact]</c> -- skipped
    /// by <c>dotnet test --filter Category!=Integration</c>, run only when this environment's own
    /// configuration actually resolves a reachable server. No row/column VALUES are asserted --
    /// this tool has no access to real data, only to the fact that a well-formed query against a
    /// reachable server should not throw.
    ///
    /// The Integration test's own <c>uow</c> is a REAL <c>PackageHarness.NewRealUnitOfWorkAsync()</c>,
    /// not <c>NewUnitOfWork()</c>'s <c>FakeUnitOfWork</c> -- caught 2026-09-06 verifying this row for
    /// real: <c>SqlRowSource&lt;TRow&gt;</c> unconditionally attempts <c>sp_bindsession</c> when
    /// given a non-null <c>uow</c>, and a <c>FakeUnitOfWork</c>'s own bind token is always the same
    /// hardcoded placeholder string, which any real server rejects with "Session binding token is
    /// invalid" regardless of what server <c>PackageHarness</c>'s <c>DatabaseOptions</c> points at.
    /// A real, already-BEGUN <c>UnitOfWork</c> is what production code actually pairs with this call
    /// too (see <c>PackageClassEmitter</c>'s own bootstrap), so this is the faithful test, not a
    /// workaround.</summary>
    /// <param name="isSecondaryConnection">Phase 5 (2026-09-17): true when this source's own
    /// connection manager resolves to a DIFFERENT database than the package's primary one (see
    /// <see cref="Ssis.Extract.Codegen.SqlFlowSource"/>'s own doc comment) -- the generated source
    /// method then takes NO <c>uow</c> argument at all (it builds its own connection string from
    /// <c>SecondaryConnections:{name}</c> config instead), so neither test constructs one. The
    /// Integration test still needs a human to point <c>PackageHarness</c>'s own
    /// <c>SecondaryConnections:{name}</c> entry at a reachable server first -- deliberately
    /// unreachable by default, the same "unreachableSecondaryServer" pattern
    /// <c>TestDoublesEmitter</c> already established for the write-side case.</param>
    public static GeneratedFile EmitSqlSourceTest(
        string testNamespace, string rootNamespace, string rowTypeNamespace, string rowTypeName,
        string sourceMethodName, string componentName, bool isSecondaryConnection = false)
    {
        var nameLiteral = ProgramEmitter.CSharpStringLiteral(componentName);
        var sourceCallArgs = isSecondaryConnection ? "" : "uow";
        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {sourceMethodName}(), proving",
            "// it constructs correctly and reports its own Name -- SqlRowSource<TRow>'s own",
            "// constructor never opens a connection, so this needs no real database. A second,",
            "// [Trait(\"Category\", \"Integration\")]-tagged test attempts a real read; it needs whatever",
            "// server this environment's own configuration resolves and is skipped by `dotnet test",
            "// --filter Category!=Integration`. Regenerating this file freely discards any hand edits",
            "// -- move those into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
            $"using {rowTypeNamespace};",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {sourceMethodName}SourceTests",
            "{",
            "    [Fact]",
            $"    public void {sourceMethodName}_ReportsItsOwnName()",
            "    {",
            "        using var harness = new PackageHarness();",
            "        var package = harness.Package();",
        };
        if (!isSecondaryConnection) lines.Add("        var uow = harness.NewUnitOfWork();");
        lines.Add("");
        lines.Add($"        var source = package.{sourceMethodName}({sourceCallArgs});");
        lines.Add("");
        lines.Add($"        Assert.Equal({nameLiteral}, source.Name);");
        lines.Add("    }");
        lines.Add("");
        lines.Add("    [Fact]");
        lines.Add("    [Trait(\"Category\", \"Integration\")]");
        lines.Add($"    public async Task {sourceMethodName}_ReadsRealRows_AgainstARealServer()");
        lines.Add("    {");
        lines.Add("        using var harness = new PackageHarness();");
        lines.Add("        var package = harness.Package();");
        if (!isSecondaryConnection) lines.Add("        await using var uow = await harness.NewRealUnitOfWorkAsync();");
        lines.Add($"        var source = package.{sourceMethodName}({sourceCallArgs});");
        lines.Add("");
        lines.Add($"        var rows = new List<{rowTypeName}>();");
        lines.Add("        await foreach (var row in source.ReadAsync(CancellationToken.None)) rows.Add(row);");
        lines.Add("");
        lines.Add("        Assert.NotNull(rows);");
        lines.Add("    }");
        lines.Add("}");

        return new GeneratedFile($"{sourceMethodName}SourceTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>"Source -- Excel" taxonomy row: <c>Docs/Generated-Tests-Plan.md</c>'s own wording
    /// is "assert .Name; full read tagged (no .xlsx writer in this stack)". Mirrors
    /// <see cref="EmitSqlSourceTest"/> exactly -- <c>ExcelRowSource&lt;TRow&gt;</c>'s own
    /// constructor is likewise plain field assignment, no file I/O until <c>ReadAsync</c> -- with
    /// one difference: an Excel source is never in <c>PackageClassEmitter.SourceNeedsUow</c>'s own
    /// true set, so its generated method takes no <c>uow</c> argument at all. The Integration tag
    /// here means "needs a real .xlsx file on disk", not necessarily a real server -- this tool has
    /// no <c>.xlsx</c> WRITER anywhere (see <c>Etl.Core.Excel.ExcelRowSource</c>'s own doc comment),
    /// so no Tier-A sample file can ever be synthesized for this source kind, unlike CSV/fixed-width.</summary>
    public static GeneratedFile EmitExcelSourceTest(
        string testNamespace, string rootNamespace, string rowTypeNamespace, string rowTypeName,
        string sourceMethodName, string componentName)
    {
        var nameLiteral = ProgramEmitter.CSharpStringLiteral(componentName);
        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {sourceMethodName}(), proving",
            "// it constructs correctly and reports its own Name -- ExcelRowSource<TRow>'s own",
            "// constructor never opens the workbook, so this needs no real file. A second,",
            "// [Trait(\"Category\", \"Integration\")]-tagged test attempts a real read; it needs a real",
            "// .xlsx file on disk (this tool has no .xlsx writer to synthesize one, unlike",
            "// CSV/fixed-width's own Tier-A sample data) and is skipped by `dotnet test --filter",
            "// Category!=Integration`. Regenerating this file freely discards any hand edits -- move",
            "// those into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
            $"using {rowTypeNamespace};",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {sourceMethodName}SourceTests",
            "{",
            "    [Fact]",
            $"    public void {sourceMethodName}_ReportsItsOwnName()",
            "    {",
            "        using var harness = new PackageHarness();",
            "        var package = harness.Package();",
            "",
            $"        var source = package.{sourceMethodName}();",
            "",
            $"        Assert.Equal({nameLiteral}, source.Name);",
            "    }",
            "",
            "    [Fact]",
            "    [Trait(\"Category\", \"Integration\")]",
            $"    public async Task {sourceMethodName}_ReadsRealRows_AgainstARealWorkbook()",
            "    {",
            "        using var harness = new PackageHarness();",
            "        var package = harness.Package();",
            $"        var source = package.{sourceMethodName}();",
            "",
            $"        var rows = new List<{rowTypeName}>();",
            "        await foreach (var row in source.ReadAsync(CancellationToken.None)) rows.Add(row);",
            "",
            "        Assert.NotNull(rows);",
            "    }",
            "}",
        };

        return new GeneratedFile($"{sourceMethodName}SourceTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>"File System Task" taxonomy row. Deliberately scoped to the one real evidenced
    /// shape -- <c>Copy</c>, with BOTH source and destination resolved from a FILE connection
    /// manager (<see cref="FileSystemActionPlan"/>'s own doc comment names the
    /// object-model-confirmed-but-never-evidenced literal-path form, and every operation other
    /// than Copy, as unevidenced) -- writing a real source file via
    /// <c>harness.FileSystemTaskPath</c> and reading the destination back afterward, the same
    /// "write to a real, isolated temp path and read the actual bytes back rather than
    /// re-implementing the runtime's own logic a second time" discipline
    /// <see cref="EmitFlatFileSinkTest"/> already uses for <c>FlatFileBulkSink</c> -- here for
    /// <c>FileSystemActionRunner</c>'s own <c>File.Copy</c> call. No test (and no gap -- this is
    /// genuinely out of pilot scope, not a newly-discovered problem) for Move/Delete/Rename/
    /// CreateDirectory, the literal-path form, or the degenerate case where the source and
    /// destination happen to resolve to the same connection manager.</summary>
    /// <summary>The one shape both <see cref="EmitFileSystemTaskTest"/> and
    /// <see cref="EmitSequenceContainerTest"/> can build a real, deterministic assertion for --
    /// see <see cref="EmitFileSystemTaskTest"/>'s own doc comment for exactly why. Kept as one
    /// shared check so the two emitters' own scope boundaries can never drift apart.</summary>
    internal static bool TryGetTestableFileSystemKeys(FileSystemActionPlan action, out string sourceKey, out string destKey)
    {
        sourceKey = "";
        destKey = "";
        if (action.Operation != "Copy") return false;
        if (action.SourceConnectionName is not { } s || action.DestinationConnectionName is not { } d) return false;
        if (s == d) return false;
        sourceKey = s;
        destKey = d;
        return true;
    }

    public static GeneratedFile? EmitFileSystemTaskTest(
        string testNamespace, string rootNamespace, string taskName, FileSystemActionPlan action)
    {
        if (!TryGetTestableFileSystemKeys(action, out var sourceKey, out var destKey)) return null;

        // taskName is the raw SSIS task display name (free text) -- must match the SANITIZED
        // method name PackageClassEmitter actually emits on the package class, since this test
        // calls that method directly (package.{safeTaskName}(...) below). See
        // PackageGenerator.SanitizeIdentifier's own doc comment.
        var safeTaskName = PackageGenerator.SanitizeIdentifier(taskName);
        var contentLiteral = ProgramEmitter.CSharpStringLiteral("ssisx starter-test file-system-task content");
        var sourceKeyLiteral = ProgramEmitter.CSharpStringLiteral(sourceKey);
        var destKeyLiteral = ProgramEmitter.CSharpStringLiteral(destKey);

        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {taskName}, proving it copies a",
            "// real source file to its destination with no database involved. Regenerating this file",
            "// freely discards any hand edits -- move those into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {safeTaskName}StepTests",
            "{",
            "    [Fact]",
            $"    public async Task {safeTaskName}_CopiesTheSourceFileToTheDestination()",
            "    {",
            "        using var harness = new PackageHarness();",
            $"        await File.WriteAllTextAsync(harness.FileSystemTaskPath({sourceKeyLiteral}), {contentLiteral});",
            "        var package = harness.Package();",
            "        var uow = harness.NewUnitOfWork();",
            "",
            $"        await package.{safeTaskName}(uow, CancellationToken.None);",
            "",
            $"        var destinationPath = harness.FileSystemTaskPath({destKeyLiteral});",
            "        Assert.True(File.Exists(destinationPath));",
            $"        Assert.Equal({contentLiteral}, await File.ReadAllTextAsync(destinationPath));",
            "    }",
            "}",
        };

        return new GeneratedFile($"{safeTaskName}StepTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>"Sequence container" taxonomy row: <c>Docs/Generated-Tests-Plan.md</c>'s own
    /// wording is "assert children ran, in order, via the fake's recorders + file effects" --
    /// deliberately scoped to a container whose DIRECT children are ALL either an ordinary Execute
    /// SQL Task (<see cref="ProgramSqlStep"/>, order asserted via <c>uow.ExecutedSql</c>'s own list
    /// position -- the "fake's recorders" half) or a Copy-shaped File System Task
    /// (<see cref="TryGetTestableFileSystemKeys"/>, existence/content asserted via
    /// <c>harness.FileSystemTaskPath</c> -- the "file effects" half, real evidence
    /// (<c>Package_Advanced.dtsx</c>'s own <c>SEQ_Prepare</c>) mixes exactly these two kinds). ANY
    /// other child kind (a Data Flow Task, Script Task, ForEach loop, a nested Sequence Container,
    /// Conditional Split/Multicast, ...) -- or a File System Task child that itself falls outside
    /// <see cref="TryGetTestableFileSystemKeys"/>'s own scope -- takes the WHOLE container out of
    /// this pilot's scope: no test, no gap (genuinely unsupported, not a guess at what running it
    /// would do). Relative ORDER is asserted only among the SQL children specifically (via
    /// consecutive index-position comparisons on the SAME shared <c>uow.ExecutedSql</c> list) --
    /// there is no shared "did X run before Y" signal across a SQL child and a File System Task
    /// child at all (the latter never touches <c>IUnitOfWork</c>, see <c>FileSystemStep</c>'s own
    /// doc comment), so a mixed container only proves each child ran, not their relative
    /// order.</summary>
    public static GeneratedFile? EmitSequenceContainerTest(
        string testNamespace, string rootNamespace, string containerMethodName, IReadOnlyList<ProgramStep> directChildren)
    {
        if (directChildren.Count == 0) return null;
        if (directChildren.Any(c => c is not ProgramSqlStep and not ProgramFileSystemStep)) return null;

        var setupLines = new List<string>();
        var assertLines = new List<string>();
        var sqlStatementRefs = new List<string>(); // one C# expression per SQL child, in real order

        foreach (var child in directChildren)
        {
            switch (child)
            {
                case ProgramSqlStep sqlStep:
                {
                    var statementRef = $"{sqlStep.StatementClassName}.BuildStatement()";
                    sqlStatementRefs.Add(statementRef);
                    assertLines.Add($"        Assert.Contains({statementRef}, uow.ExecutedSql);");
                    break;
                }
                case ProgramFileSystemStep fsStep:
                {
                    if (!TryGetTestableFileSystemKeys(fsStep.Action, out var sourceKey, out var destKey)) return null;
                    var contentLiteral = ProgramEmitter.CSharpStringLiteral($"ssisx starter-test content for {fsStep.StepName}");
                    var sourceKeyLiteral = ProgramEmitter.CSharpStringLiteral(sourceKey);
                    var destKeyLiteral = ProgramEmitter.CSharpStringLiteral(destKey);
                    setupLines.Add($"        await File.WriteAllTextAsync(harness.FileSystemTaskPath({sourceKeyLiteral}), {contentLiteral});");
                    assertLines.Add($"        Assert.True(File.Exists(harness.FileSystemTaskPath({destKeyLiteral})));");
                    assertLines.Add($"        Assert.Equal({contentLiteral}, await File.ReadAllTextAsync(harness.FileSystemTaskPath({destKeyLiteral})));");
                    break;
                }
            }
        }

        // Order is only meaningful, and only asserted, among consecutive SQL children -- a File
        // System Task child never touches uow.ExecutedSql at all (see this method's own doc
        // comment), so there is nothing to compare it against.
        for (var i = 0; i + 1 < sqlStatementRefs.Count; i++)
            assertLines.Add($"        Assert.True(uow.ExecutedSql.IndexOf({sqlStatementRefs[i]}) < uow.ExecutedSql.IndexOf({sqlStatementRefs[i + 1]}));");

        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {containerMethodName}, proving",
            "// every direct child this pilot can observe actually ran (and, for consecutive Execute SQL",
            "// Task children, ran in the declared order) with no real database involved. Regenerating",
            "// this file freely discards any hand edits -- move those into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
            $"using {rootNamespace}.Mapping;",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {containerMethodName}StepTests",
            "{",
            "    [Fact]",
            $"    public async Task {containerMethodName}_RunsEveryChild()",
            "    {",
            "        using var harness = new PackageHarness();",
        };
        lines.AddRange(setupLines);
        lines.Add("        var package = harness.Package();");
        lines.Add("        var uow = harness.NewUnitOfWork();");
        lines.Add("");
        lines.Add($"        await package.{containerMethodName}(uow, CancellationToken.None);");
        lines.Add("");
        lines.AddRange(assertLines);
        lines.Add("    }");
        lines.Add("}");

        return new GeneratedFile($"{containerMethodName}StepTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>"OLE DB Command" taxonomy row: <c>Docs/Generated-Tests-Plan.md</c>'s own wording is
    /// "assert uow.ExecutedParameterizedSql -- template + one parameter array per row". Deliberately
    /// bypasses the flow's own generated source method entirely -- the one real evidenced case
    /// (RBC_Demo_ETL's own DFT_FlagCustomers) reads its source from a real SQL connection, which
    /// this pilot's "no [server]" bar rules out -- and instead constructs
    /// <c>Etl.Core.Pipeline.OleDbCommandStep&lt;TRow&gt;</c> directly against a tiny, private,
    /// in-memory stub <c>IRowSource&lt;TRow&gt;</c> built from two synthesized rows: the same
    /// "test the smallest possible unit of work in isolation" acceptance bar
    /// <c>Docs/Emitter-Rewrite-Plan.md</c>'s own §8 states, applied here to the STEP itself rather
    /// than to whatever produces its rows. Synthesized rows reuse the flow's own resolved source
    /// columns (name + CLR type, from <see cref="PipelineResolver"/> -- the exact columns
    /// SqlRowEmitter/CsvRowEmitter/ExcelRowEmitter already build the row type's own properties
    /// from) and <see cref="TransformTestEmitter.RepresentativeLiteral"/>'s shared values, so a
    /// column this pilot cannot represent (no resolvable CLR type) is simply left off the
    /// synthesized row -- unless that column happens to be one of the command's OWN parameter
    /// columns, in which case there is nothing safe to assert about the parameter array's
    /// contents at all, and this pilot emits no test (and no gap -- the missing type is already
    /// reported elsewhere, by whichever row-type emitter first tried to use it).</summary>
    public static GeneratedFile? EmitOleDbCommandTest(
        string testNamespace, string rootNamespace, string rowTypeNamespace, string rowTypeName,
        string stepName, string sqlTemplate, IReadOnlyList<string> parameterColumnNames,
        IReadOnlyList<ResolvedColumn> sourceColumns)
    {
        var literalsByName = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var column in sourceColumns)
        {
            if (column.Type is not { } clrType) continue;
            literalsByName[column.PipelineColumnName] = TransformTestEmitter.RepresentativeLiteral(clrType.ClrTypeName);
        }

        if (parameterColumnNames.Count == 0) return null;
        if (parameterColumnNames.Any(p => !literalsByName.ContainsKey(p))) return null;

        // stepName is the raw SSIS component display name (free text) -- sanitized for the
        // class/method/file-name positions below; stepNameLiteral (the runtime label the
        // reconstructed step itself carries) is built from the ORIGINAL, unsanitized name, same
        // as the real generated code does.
        var safeStepName = PackageGenerator.SanitizeIdentifier(stepName);
        // literalsByName is keyed by the RAW source column name (matching parameterColumnNames'
        // own raw entries, so the ContainsKey/lookup checks above stay simple); only the two
        // EMISSION points below (the synthesized row's own object initializer and the parameter
        // accessor) need the sanitized C# identifier -- see
        // PackageGenerator.SanitizeIdentifier's own doc comment.
        var propertyInits = string.Join(", ", literalsByName.Select(kv => $"{PackageGenerator.SanitizeIdentifier(kv.Key)} = {kv.Value}"));
        var parameterArrayLiteral = $"new object?[] {{ {string.Join(", ", parameterColumnNames.Select(p => literalsByName[p]))} }}";
        var parameterAccessExpr = string.Join(", ", parameterColumnNames.Select(p => $"row.{PackageGenerator.SanitizeIdentifier(p)}"));
        var sqlTemplateLiteral = ProgramEmitter.CSharpStringLiteral(sqlTemplate);
        var stepNameLiteral = ProgramEmitter.CSharpStringLiteral(stepName);

        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {stepName}, proving",
            "// OleDbCommandStep<TRow> runs its own SQL template once per row with the right",
            "// parameters -- using a synthesized in-memory row source rather than the flow's own real",
            "// source (which may need a real database; this test never does). Regenerating this file",
            "// freely discards any hand edits -- move those into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
            "using System.Runtime.CompilerServices;",
            "using Etl.Core.Abstractions;",
            "using Etl.Core.Pipeline;",
            $"using {rowTypeNamespace};",
            $"using {rootNamespace}.TestDoubles;",
            "using Microsoft.Extensions.Logging.Abstractions;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {safeStepName}StepTests",
            "{",
            "    [Fact]",
            $"    public async Task {safeStepName}_RunsTheCommandOncePerRow_WithTheRightParameters()",
            "    {",
            "        using var harness = new PackageHarness();",
            "        var uow = harness.NewUnitOfWork();",
            "        var rows = new[]",
            "        {",
            $"            new {rowTypeName} {{ {propertyInits} }},",
            $"            new {rowTypeName} {{ {propertyInits} }},",
            "        };",
            "        var source = new StubRowSource(rows);",
            $"        var step = new OleDbCommandStep<{rowTypeName}>(",
            $"            {stepNameLiteral},",
            "            source,",
            $"            {sqlTemplateLiteral},",
            $"            row => new object?[] {{ {parameterAccessExpr} }},",
            $"            NullLogger<OleDbCommandStep<{rowTypeName}>>.Instance);",
            "",
            "        await step.RunAsync(uow, new LoadContext(Guid.NewGuid(), DateTime.UtcNow, \"Test\"), CancellationToken.None);",
            "",
            "        Assert.Equal(2, uow.ExecutedParameterizedSql.Count);",
            "        foreach (var call in uow.ExecutedParameterizedSql)",
            "        {",
            $"            Assert.Equal({sqlTemplateLiteral}, call.Sql);",
            $"            Assert.Equal({parameterArrayLiteral}, call.Parameters);",
            "        }",
            "    }",
            "",
            $"    private sealed class StubRowSource(IReadOnlyList<{rowTypeName}> rows) : IRowSource<{rowTypeName}>",
            "    {",
            $"        public string Name => {stepNameLiteral};",
            "",
            $"        public async IAsyncEnumerable<{rowTypeName}> ReadAsync([EnumeratorCancellation] CancellationToken ct)",
            "        {",
            "            foreach (var row in rows) yield return row;",
            "            await Task.CompletedTask;",
            "        }",
            "    }",
            "}",
        };

        return new GeneratedFile($"{safeStepName}StepTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>"ForEach loop" taxonomy row: <c>Docs/Generated-Tests-Plan.md</c>'s own wording is
    /// "temp dir with 2 files; assert 2 substituted statements in ExecutedSql, ordinal file order".
    /// Targets <see cref="ProgramForEachFileLoopStep"/> -- the real evidenced shape
    /// (<c>Package_Advanced.dtsx</c>'s own <c>FEL_SampleFiles</c>: a single Execute SQL Task whose
    /// SQL is rebuilt per file). <c>ForEachLoopStep.RunAsync</c>'s own real implementation (see
    /// <c>Etl.Core</c>) enumerates <c>Directory.EnumerateFiles(Folder, FileSpec, ...)</c> sorted
    /// ORDINALLY, computes <c>currentFile</c> per <c>NameMode</c>
    /// (<c>Path.GetFileName</c>/<c>GetFileNameWithoutExtension</c>/the raw path), then calls
    /// <c>uow.ExecuteSqlAsync(buildSql(currentFile), ct)</c> -- so this test writes two real files
    /// into <c>harness.ForEachLoopFolder(key)</c> (a real, pre-created, per-key temp folder --
    /// <c>TestDoublesEmitter</c>'s own <c>forEachLoopKeys</c> wiring) named so they sort "a" before
    /// "b" ordinally, then asserts BOTH substituted <c>{StatementClassName}.BuildStatement(...)</c>
    /// calls appear in <c>uow.ExecutedSql</c>, in that order -- calling the SAME
    /// <c>BuildStatement</c> the generated code itself calls, never re-deriving the substitution.
    /// Only a single-wildcard <c>fileSpec</c> ("*.ext" or bare "*") is supported -- anything more
    /// complex (multiple wildcards, "?" placeholders) is out of pilot scope: no test, no gap (see
    /// <see cref="TryBuildTestFileNames"/>).</summary>
    public static GeneratedFile? EmitForEachLoopTest(
        string testNamespace, string rootNamespace, string stepName, string fileSourceKey, string fileSpec,
        string nameMode, string statementClassName)
    {
        if (!TryBuildTestFileNames(fileSpec, out var name1, out var name2)) return null;

        // stepName is the raw SSIS component display name -- must match the SANITIZED method name
        // PackageClassEmitter actually emits, since this test calls that method directly
        // (package.{safeStepName}(...) below).
        var safeStepName = PackageGenerator.SanitizeIdentifier(stepName);
        var keyLiteral = ProgramEmitter.CSharpStringLiteral(fileSourceKey);

        // The C# EXPRESSION passed to BuildStatement -- matching exactly what ForEachLoopStep's
        // own real currentFile computation would produce for this file, at TEST-RUN time (the
        // FullyQualified case needs the real temp folder path, only known then, not a literal).
        string CurrentFileExpr(string fileName) => nameMode switch
        {
            "NameAndExtension" => ProgramEmitter.CSharpStringLiteral(fileName),
            "NameOnly" => ProgramEmitter.CSharpStringLiteral(Path.GetFileNameWithoutExtension(fileName)),
            _ => $"Path.Combine(harness.ForEachLoopFolder({keyLiteral}), {ProgramEmitter.CSharpStringLiteral(fileName)})",
        };

        var statement1 = $"{statementClassName}.BuildStatement({CurrentFileExpr(name1)})";
        var statement2 = $"{statementClassName}.BuildStatement({CurrentFileExpr(name2)})";

        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {stepName}, proving it",
            "// rebuilds its own SQL statement once per file, in ordinal file order, with no real",
            "// database involved. Regenerating this file freely discards any hand edits -- move those",
            "// into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
            $"using {rootNamespace}.Mapping;",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {safeStepName}StepTests",
            "{",
            "    [Fact]",
            $"    public async Task {safeStepName}_ExecutesOneStatementPerFile_InOrdinalFileOrder()",
            "    {",
            "        using var harness = new PackageHarness();",
            $"        await File.WriteAllTextAsync(Path.Combine(harness.ForEachLoopFolder({keyLiteral}), {ProgramEmitter.CSharpStringLiteral(name1)}), \"a\");",
            $"        await File.WriteAllTextAsync(Path.Combine(harness.ForEachLoopFolder({keyLiteral}), {ProgramEmitter.CSharpStringLiteral(name2)}), \"b\");",
            "        var package = harness.Package();",
            "        var uow = harness.NewUnitOfWork();",
            "",
            $"        await package.{safeStepName}(uow, CancellationToken.None);",
            "",
            $"        Assert.Contains({statement1}, uow.ExecutedSql);",
            $"        Assert.Contains({statement2}, uow.ExecutedSql);",
            $"        Assert.True(uow.ExecutedSql.IndexOf({statement1}) < uow.ExecutedSql.IndexOf({statement2}));",
            "    }",
            "}",
        };

        return new GeneratedFile($"{safeStepName}StepTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>The one shape this pilot can build 2 real, distinct, ordinal-sortable file names
    /// for -- a single "*" wildcard, either bare or followed by a literal extension. Anything more
    /// complex (multiple wildcards, "?" placeholders, a literal prefix before the "*") is out of
    /// pilot scope: no test, no gap (genuinely unsupported, not a guess at what such a pattern
    /// would mean).</summary>
    internal static bool TryBuildTestFileNames(string fileSpec, out string name1, out string name2)
    {
        name1 = "";
        name2 = "";
        if (fileSpec == "*")
        {
            name1 = "a.dat";
            name2 = "b.dat";
            return true;
        }
        if (fileSpec.StartsWith("*.", StringComparison.Ordinal)
            && fileSpec.IndexOf('*', 1) < 0 && fileSpec.IndexOf('?') < 0)
        {
            var ext = fileSpec[1..]; // ".ext"
            name1 = "a" + ext;
            name2 = "b" + ext;
            return true;
        }
        return false;
    }

    /// <summary>One Multicast branch's own facts, resolved by <c>GenerateMulticastFlow</c> --
    /// enough for <see cref="EmitMulticastTest"/> to construct the SAME kind of
    /// <c>ConditionalSplitBranch&lt;TRow,TEntity&gt;</c> the generated step method itself builds,
    /// without needing the entity/sink's own generated method (a Multicast branch's sink is
    /// constructed INLINE inside the step's own method, never as an independently-callable method
    /// the way an ordinary single-destination flow's sink is -- see
    /// <c>PackageClassEmitter</c>'s own <c>ProgramMulticastStep</c> case).</summary>
    public sealed record MulticastTestBranch(string OutputName, string EntityNamespace, string EntityName, string TransformClassName, FlowSinkSpec Sink);

    /// <summary>"Multicast" taxonomy row: <c>Docs/Generated-Tests-Plan.md</c>'s own wording is
    /// "assert every branch received every row". Deliberately bypasses the flow's own generated
    /// source AND sink construction entirely -- the one real evidenced case
    /// (RBC_Demo_ETL's own <c>Package_Legacy.dtsx</c>'s own <c>MCAST_FixedRows</c>) reads from a
    /// FIXED-WIDTH flat file (no Tier-A sample data support yet -- see the "fixed-width source"
    /// taxonomy row) and its own Flat File Destination branch is never wired to a standalone,
    /// independently-callable sink method the way an ordinary flow's sink is (see
    /// <see cref="MulticastTestBranch"/>'s own doc comment) -- so this constructs
    /// <c>MulticastStep&lt;TRow&gt;</c> directly against a synthesized 2-row in-memory stub source,
    /// the same "test the smallest possible unit of work in isolation" acceptance bar
    /// <see cref="EmitOleDbCommandTest"/> already established for the identical reason. A SQL
    /// branch's own <c>SqlBulkSink&lt;TEntity&gt;</c> is faked via <c>uow.BulkInserts</c> exactly
    /// like <see cref="EmitSqlSinkTest"/>; a Flat File branch's own <c>FlatFileBulkSink&lt;TEntity&gt;</c>
    /// never touches <c>IUnitOfWork</c> at all (see that type's own doc comment), so it writes to a
    /// real, isolated temp file this test creates and deletes itself (no <c>PackageHarness</c>
    /// wiring needed, since this branch's own key is never registered in
    /// <c>FileSourceOptions</c> either) and reads the real bytes back -- the same "write for real,
    /// read the actual bytes back" discipline <see cref="EmitFlatFileSinkTest"/> already uses,
    /// applied to a sink this pilot cannot reach through a generated method. No test (and no gap --
    /// every column this pilot cannot represent, or a branch with no live columns, is already
    /// reported elsewhere) when nothing here can synthesize a full source row or there are no
    /// branches to assert.</summary>
    public static GeneratedFile? EmitMulticastTest(
        string testNamespace, string rootNamespace, string rowTypeNamespace, string rowTypeName,
        string stepName, IReadOnlyList<ResolvedColumn> sourceColumns, IReadOnlyList<MulticastTestBranch> branches)
    {
        if (branches.Count == 0) return null;

        var literalsByName = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var column in sourceColumns)
        {
            if (column.Type is not { } clrType) continue;
            literalsByName[column.PipelineColumnName] = TransformTestEmitter.RepresentativeLiteral(clrType.ClrTypeName);
        }
        if (literalsByName.Count == 0) return null;

        // stepName is the raw SSIS component display name -- sanitized for the class/method/
        // file-name positions below; every ProgramEmitter.CSharpStringLiteral(stepName) call
        // below builds the reconstructed step's own RUNTIME label from the original name, same as
        // the real generated code does.
        var safeStepName = PackageGenerator.SanitizeIdentifier(stepName);

        // literalsByName is keyed by the RAW source column name -- sanitized at this one emission
        // point (the synthesized row's own object initializer), see
        // PackageGenerator.SanitizeIdentifier's own doc comment.
        var propertyInits = string.Join(", ", literalsByName.Select(kv => $"{PackageGenerator.SanitizeIdentifier(kv.Key)} = {kv.Value}"));
        var entityNamespaces = branches.Select(b => b.EntityNamespace).Distinct(StringComparer.Ordinal).ToList();

        var branchLines = new List<string>();
        var flatFileTempVars = new List<(string TempVar, bool HasHeader)>();
        for (var i = 0; i < branches.Count; i++)
        {
            var branch = branches[i];
            var comma = i < branches.Count - 1 ? "," : "";
            var nameLiteral = ProgramEmitter.CSharpStringLiteral(branch.OutputName);
            if (branch.Sink is FlatFileFlowSink ffs)
            {
                var tempVar = $"tempFile{i}";
                flatFileTempVars.Add((tempVar, ffs.HeaderLine is not null));
                var columns = string.Join(", ", ffs.Columns.Select(c =>
                    $"new FlatFileColumnFormat({ProgramEmitter.CSharpStringLiteral(c.PropertyName)}, {(c.FixedWidth is { } w ? w.ToString() : "null")}, {ProgramEmitter.CSharpStringLiteral(c.Delimiter)})"));
                var header = ffs.HeaderLine is null ? "null" : ProgramEmitter.CSharpStringLiteral(ffs.HeaderLine);
                branchLines.Add($"            new ConditionalSplitBranch<{rowTypeName}, {branch.EntityName}>({nameLiteral}, new {branch.TransformClassName}(), new FlatFileBulkSink<{branch.EntityName}>({tempVar}, true, {header}, [{columns}], NullLogger<FlatFileBulkSink<{branch.EntityName}>>.Instance)){comma}");
            }
            else
            {
                branchLines.Add($"            new ConditionalSplitBranch<{rowTypeName}, {branch.EntityName}>({nameLiteral}, new {branch.TransformClassName}(), new SqlBulkSink<{branch.EntityName}>(Options.Create(new BulkCopyOptions()), NullLogger<SqlBulkSink<{branch.EntityName}>>.Instance)){comma}");
            }
        }
        var sqlBranchCount = branches.Count(b => b.Sink is SqlFlowSink);

        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {stepName}, proving every",
            "// branch receives every row -- using a synthesized in-memory row source and, for any Flat",
            "// File Destination branch, a real isolated temp file (no real SQL Server involved).",
            "// Regenerating this file freely discards any hand edits -- move those into a second file",
            "// instead.",
            "// </auto-generated>",
            "#nullable enable",
            "using System.Runtime.CompilerServices;",
            "using Etl.Core.Abstractions;",
            "using Etl.Core.Data;",
            "using Etl.Core.Pipeline;",
            $"using {rowTypeNamespace};",
            $"using {rootNamespace}.Mapping;",
        };
        foreach (var ns in entityNamespaces) lines.Add($"using {ns};");
        lines.Add($"using {rootNamespace}.TestDoubles;");
        lines.Add("using Microsoft.Extensions.Logging.Abstractions;");
        lines.Add("using Microsoft.Extensions.Options;");
        lines.Add("using Xunit;");
        lines.Add("");
        lines.Add($"namespace {testNamespace};");
        lines.Add("");
        lines.Add($"public class {safeStepName}StepTests");
        lines.Add("{");
        lines.Add("    [Fact]");
        lines.Add($"    public async Task {safeStepName}_RunsEveryBranch_ForEveryRow()");
        lines.Add("    {");
        lines.Add("        using var harness = new PackageHarness();");
        lines.Add("        var uow = harness.NewUnitOfWork();");
        foreach (var (tempVar, _) in flatFileTempVars)
            lines.Add($"        var {tempVar} = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString(\"N\") + \".txt\");");
        lines.Add("        try");
        lines.Add("        {");
        lines.Add("            var rows = new[]");
        lines.Add("            {");
        lines.Add($"                new {rowTypeName} {{ {propertyInits} }},");
        lines.Add($"                new {rowTypeName} {{ {propertyInits} }},");
        lines.Add("            };");
        lines.Add("            var source = new StubRowSource(rows);");
        lines.Add($"            var branches = new IConditionalSplitBranch<{rowTypeName}>[]");
        lines.Add("            {");
        lines.AddRange(branchLines);
        lines.Add("            };");
        lines.Add($"            var step = new MulticastStep<{rowTypeName}>({ProgramEmitter.CSharpStringLiteral(stepName)}, source, branches, NullLogger<MulticastStep<{rowTypeName}>>.Instance);");
        lines.Add("");
        lines.Add("            await step.RunAsync(uow, new LoadContext(Guid.NewGuid(), DateTime.UtcNow, \"Test\"), CancellationToken.None);");
        lines.Add("");
        // xUnit2013: Assert.Equal(N, x.Count) for N=0 or 1 is a build ERROR under this project's
        // analyzer settings (TreatWarningsAsErrors=true) -- Assert.Empty/Assert.Single are required.
        lines.Add(sqlBranchCount switch
        {
            0 => "            Assert.Empty(uow.BulkInserts);",
            1 => "            Assert.Single(uow.BulkInserts);",
            _ => $"            Assert.Equal({sqlBranchCount}, uow.BulkInserts.Count);",
        });
        lines.Add("            Assert.All(uow.BulkInserts, call => Assert.Equal(2, call.RowsWritten));");
        foreach (var (tempVar, hasHeader) in flatFileTempVars)
        {
            var expectedLines = hasHeader ? 3 : 2;
            lines.Add($"            Assert.True(File.Exists({tempVar}));");
            lines.Add($"            Assert.Equal({expectedLines}, (await File.ReadAllLinesAsync({tempVar})).Length);");
        }
        lines.Add("        }");
        lines.Add("        finally");
        lines.Add("        {");
        foreach (var (tempVar, _) in flatFileTempVars)
            lines.Add($"            if (File.Exists({tempVar})) File.Delete({tempVar});");
        lines.Add("        }");
        lines.Add("    }");
        lines.Add("");
        lines.Add($"    private sealed class StubRowSource(IReadOnlyList<{rowTypeName}> rows) : IRowSource<{rowTypeName}>");
        lines.Add("    {");
        lines.Add($"        public string Name => {ProgramEmitter.CSharpStringLiteral(stepName)};");
        lines.Add("");
        lines.Add($"        public async IAsyncEnumerable<{rowTypeName}> ReadAsync([EnumeratorCancellation] CancellationToken ct)");
        lines.Add("        {");
        lines.Add("            foreach (var row in rows) yield return row;");
        lines.Add("            await Task.CompletedTask;");
        lines.Add("        }");
        lines.Add("    }");
        lines.Add("}");

        return new GeneratedFile($"{safeStepName}StepTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>One Count function on an Aggregate flow, resolved by
    /// <c>GenerateAggregateFlow</c>/<c>EmitAggregateRowEntityAndTransform</c> -- enough for
    /// <see cref="EmitAggregateSourceTest"/> to synthesize a source row with the right CLR type for
    /// the counted column, without re-resolving <c>PipelineResolver</c> a second time.</summary>
    public sealed record AggregateSourceTestFunction(string OutputPropertyName, string SourcePropertyName, string SourcePropertyClrType, int AggregationTypeRaw);

    /// <summary>"Aggregate source" taxonomy row: <c>Docs/Generated-Tests-Plan.md</c>'s own wording
    /// is "synthesized rows -&gt; assert grouped keys and counts". Bypasses the flow's own real
    /// source entirely -- an Aggregate flow's own source is REQUIRED to be SQL
    /// (<c>GenerateAggregateFlow</c> gaps out any other source kind), which this pilot's "no
    /// [server]" bar rules out -- and instead constructs
    /// <c>Etl.Core.Data.AggregateRowSource&lt;TSourceRow,TKey,TRow&gt;</c> directly against a tiny,
    /// private, in-memory stub <c>IRowSource&lt;TSourceRow&gt;</c>, the same "test the smallest
    /// possible unit of work in isolation" acceptance bar <see cref="EmitOleDbCommandTest"/>
    /// already established for the identical reason. <c>AggregateRowSource</c> needs no
    /// <c>IUnitOfWork</c>/<c>PackageHarness</c> at all -- it is a pure in-memory grouping
    /// operation, so this is the one starter test in this whole emitter with literally nothing to
    /// fake. Deliberately scoped to the one evidenced/reachable shape: a string GroupBy key (the
    /// real evidenced <c>AGG_ByRegion</c>'s own "Region") and AggregationType=1 (Count, excluding
    /// NULL -- the only type <c>PackagePlanner.PlanAggregate</c> actually accepts; see
    /// <c>AggregatePayload</c>'s own doc comment) -- anything else (a non-string GroupBy key,
    /// Sum/Average/Minimum/Maximum/CountDistinct/CountAll) is out of pilot scope: no test, no gap
    /// (this tool does not even generate those shapes yet, so there is nothing to test).</summary>
    public static GeneratedFile? EmitAggregateSourceTest(
        string testNamespace, string rootNamespace,
        string sourceRowTypeNamespace, string sourceRowTypeName,
        string aggregateRowTypeNamespace, string aggregateRowTypeName,
        string componentName, string groupByPropertyName, string groupByKeyClrType,
        IReadOnlyList<AggregateSourceTestFunction> functions)
    {
        if (functions.Count == 0) return null;
        if (functions.Any(f => f.AggregationTypeRaw != 1)) return null;
        if (groupByKeyClrType != "string") return null;

        // groupByPropertyName/fn.SourcePropertyName/fn.OutputPropertyName are all raw column
        // names -- sanitized here, once, for every identifier-position use below (a SOURCE row
        // reference or the Aggregate row's own destination property, see
        // PackageGenerator.SanitizeIdentifier's own doc comment).
        var groupByIdentifier = PackageGenerator.SanitizeIdentifier(groupByPropertyName);

        // GroupA gets 3 rows -- 2 with a real value for the FIRST function's own counted column,
        // 1 with null for it -- so the same scenario proves both grouping (2 distinct keys) and
        // NULL-exclusion (GroupA's own count for that function is 2, not 3) in one synthesized set.
        // GroupB gets exactly 1 row, all counted columns populated.
        var nullExclusionColumn = functions[0].SourcePropertyName;
        string RowInit(string groupValue, bool nullOutFirstFunction)
        {
            var assigns = new List<string> { $"{groupByIdentifier} = {ProgramEmitter.CSharpStringLiteral(groupValue)}" };
            foreach (var fn in functions)
            {
                var srcId = PackageGenerator.SanitizeIdentifier(fn.SourcePropertyName);
                assigns.Add(nullOutFirstFunction && fn.SourcePropertyName == nullExclusionColumn
                    ? $"{srcId} = null"
                    : $"{srcId} = {TransformTestEmitter.RepresentativeLiteral(fn.SourcePropertyClrType)}");
            }
            return $"new {sourceRowTypeName} {{ {string.Join(", ", assigns)} }}";
        }

        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {componentName}, proving it",
            "// groups synthesized rows by key and counts non-null values within each group, with no",
            "// real database involved (AggregateRowSource is a pure in-memory grouping operation --",
            "// nothing here needs faking). Regenerating this file freely discards any hand edits --",
            "// move those into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
            "using System.Linq;",
            "using System.Runtime.CompilerServices;",
            "using Etl.Core.Abstractions;",
            "using Etl.Core.Data;",
            $"using {sourceRowTypeNamespace};",
        };
        if (!string.Equals(sourceRowTypeNamespace, aggregateRowTypeNamespace, StringComparison.Ordinal))
            lines.Add($"using {aggregateRowTypeNamespace};");
        lines.Add("using Xunit;");
        lines.Add("");
        lines.Add($"namespace {testNamespace};");
        lines.Add("");
        lines.Add($"public class {aggregateRowTypeName}SourceTests");
        lines.Add("{");
        lines.Add("    [Fact]");
        lines.Add($"    public async Task ReadAsync_GroupsRows_AndCountsNonNullValues()");
        lines.Add("    {");
        lines.Add("        var rows = new[]");
        lines.Add("        {");
        lines.Add($"            {RowInit("GroupA", nullOutFirstFunction: false)},");
        lines.Add($"            {RowInit("GroupA", nullOutFirstFunction: true)},");
        lines.Add($"            {RowInit("GroupA", nullOutFirstFunction: false)},");
        lines.Add($"            {RowInit("GroupB", nullOutFirstFunction: false)},");
        lines.Add("        };");
        lines.Add($"        var source = new AggregateRowSource<{sourceRowTypeName}, string, {aggregateRowTypeName}>(");
        lines.Add($"            {ProgramEmitter.CSharpStringLiteral(componentName)},");
        lines.Add("            new StubRowSource(rows),");
        lines.Add($"            row => row.{groupByIdentifier},");
        lines.Add($"            (key, groupedRows) => new {aggregateRowTypeName}");
        lines.Add("            {");
        lines.Add($"                {groupByIdentifier} = key,");
        for (var i = 0; i < functions.Count; i++)
        {
            var fn = functions[i];
            var comma = i < functions.Count - 1 ? "," : "";
            lines.Add($"                {PackageGenerator.SanitizeIdentifier(fn.OutputPropertyName)} = groupedRows.Count(r => r.{PackageGenerator.SanitizeIdentifier(fn.SourcePropertyName)} != null){comma}");
        }
        lines.Add("            });");
        lines.Add("");
        lines.Add($"        var results = new List<{aggregateRowTypeName}>();");
        lines.Add("        await foreach (var row in source.ReadAsync(CancellationToken.None)) results.Add(row);");
        lines.Add("");
        lines.Add("        Assert.Equal(2, results.Count);");
        lines.Add($"        var groupA = results.Single(r => r.{groupByPropertyName} == \"GroupA\");");
        lines.Add($"        var groupB = results.Single(r => r.{groupByPropertyName} == \"GroupB\");");
        foreach (var fn in functions)
        {
            lines.Add($"        Assert.Equal(2, groupA.{fn.OutputPropertyName});");
            lines.Add($"        Assert.Equal(1, groupB.{fn.OutputPropertyName});");
        }
        lines.Add("    }");
        lines.Add("");
        lines.Add($"    private sealed class StubRowSource(IReadOnlyList<{sourceRowTypeName}> rows) : IRowSource<{sourceRowTypeName}>");
        lines.Add("    {");
        lines.Add($"        public string Name => {ProgramEmitter.CSharpStringLiteral(componentName)};");
        lines.Add("");
        lines.Add($"        public async IAsyncEnumerable<{sourceRowTypeName}> ReadAsync([EnumeratorCancellation] CancellationToken ct)");
        lines.Add("        {");
        lines.Add("            foreach (var row in rows) yield return row;");
        lines.Add("            await Task.CompletedTask;");
        lines.Add("        }");
        lines.Add("    }");
        lines.Add("}");

        return new GeneratedFile($"{aggregateRowTypeName}SourceTests.cs", Rendering.JoinLines(lines));
    }

    private readonly record struct RawAssignment(string RawLiteral, string ExpectedLiteral);

    /// <summary>One raw (side, rawColumnName) pair's own representative value -- a plain
    /// passthrough uses <see cref="TransformTestEmitter.RepresentativeLiteral"/> directly (the raw
    /// literal IS the expected value, unconverted); a Data-Conversion-derived one reuses
    /// <see cref="TransformTestEmitter.RepresentativeDataConversion"/> so a Merge Join mapper
    /// test's own predicted value can never quietly drift from what <c>SsisFnEmitter</c>'s emitted
    /// <c>SsisFn.ToNullable*</c> body actually computes for the SAME raw string. Null means this
    /// pilot has nothing safe to assert (an unsupported Data Conversion target, or DT_WSTR with no
    /// declared width -- see that method's own doc comment).</summary>
    private static RawAssignment? ResolveRawAssignment(string rawColumnClrType, string? conversionTargetType, int? conversionLength)
    {
        if (conversionTargetType is not null)
        {
            var rep = TransformTestEmitter.RepresentativeDataConversion(conversionTargetType, conversionLength);
            return rep is { } r ? new RawAssignment(r.RawLiteral, r.ExpectedLiteral) : null;
        }

        var literal = TransformTestEmitter.RepresentativeLiteral(rawColumnClrType);
        return new RawAssignment(literal, literal);
    }

    /// <summary>"Merge Join mapper" taxonomy row: <c>Docs/Generated-Tests-Plan.md</c>'s own wording
    /// is "LeftKey / RightKey / Map over synthesized rows". A pure static-function test -- no
    /// <c>IUnitOfWork</c>/<c>PackageHarness</c> needed at all, since <c>{Mapper}.LeftKey</c>/
    /// <c>RightKey</c>/<c>Map</c> touch neither.
    ///
    /// <para>Two scenarios, both real-evidenced concerns for this exact code (RBC_Demo_ETL's own
    /// <c>DFT_SortAndMergeJoin</c>): a MATCHED pair (both sides present, asserting every key and
    /// every combined-row column's predicted value) and an UNMATCHED left row (<c>right</c> is
    /// <c>null</c> -- the one evidenced join type, LeftOuter, so a right-side column must come
    /// back <c>null</c> rather than throwing the exact <c>CS8629</c>/null-forgiving-<c>!</c> class
    /// of bug this generator's own Merge Join round had to fix once already). The second scenario
    /// is only emitted when at least one column is genuinely right-side (<see cref="MergeJoinEmitter.MergeJoinTestColumn.MayBeAbsent"/>);
    /// a hypothetical join type with no absent side at all would have nothing to assert there.</para>
    ///
    /// <para>Every raw (side, column-name) pair resolves through <see cref="ResolveRawAssignment"/>
    /// -- if the SAME raw column is referenced twice with two DIFFERENT resolutions (never
    /// evidenced, but checked defensively), or any one reference cannot be resolved at all (an
    /// unsupported Data Conversion target/width), no test is emitted, and no gap either -- this
    /// pilot's scope, not a newly discovered problem.</para>
    /// </summary>
    public static GeneratedFile? EmitMergeJoinMapperTest(
        string testNamespace,
        string leftRowTypeNamespace, string leftRowTypeName,
        string rightRowTypeNamespace, string rightRowTypeName,
        string mappingNamespace, string mapperClassName,
        MergeJoinEmitter.MergeJoinTestKey leftKeyTest, MergeJoinEmitter.MergeJoinTestKey rightKeyTest,
        IReadOnlyList<MergeJoinEmitter.MergeJoinTestColumn> testColumns)
    {
        var leftLiterals = new Dictionary<string, RawAssignment>(StringComparer.Ordinal);
        var rightLiterals = new Dictionary<string, RawAssignment>(StringComparer.Ordinal);

        bool TryAssign(Dictionary<string, RawAssignment> literals, string rawColumnName, string rawColumnClrType, string? conversionTargetType, int? conversionLength)
        {
            var resolved = ResolveRawAssignment(rawColumnClrType, conversionTargetType, conversionLength);
            if (resolved is not { } assignment) return false;
            if (literals.TryGetValue(rawColumnName, out var existing))
                return existing.RawLiteral == assignment.RawLiteral && existing.ExpectedLiteral == assignment.ExpectedLiteral;
            literals[rawColumnName] = assignment;
            return true;
        }

        if (!TryAssign(leftLiterals, leftKeyTest.RawColumnName, leftKeyTest.RawColumnClrType, leftKeyTest.ConversionTargetType, leftKeyTest.ConversionLength)) return null;
        if (!TryAssign(rightLiterals, rightKeyTest.RawColumnName, rightKeyTest.RawColumnClrType, rightKeyTest.ConversionTargetType, rightKeyTest.ConversionLength)) return null;

        foreach (var col in testColumns)
        {
            var literals = col.MayBeAbsent ? rightLiterals : leftLiterals;
            if (!TryAssign(literals, col.RawColumnName, col.RawColumnClrType, col.ConversionTargetType, col.ConversionLength)) return null;
        }

        // leftLiterals/rightLiterals are keyed by the RAW source column name (Left/Right's own
        // row types, matching SqlRowEmitter/CsvRowEmitter's own bare-sanitized declarations);
        // combinedIdentifierOf independently reproduces MergeJoinEmitter.BuildRowTypeFile's own
        // resolver over the SAME testColumns list, in the SAME order -- see
        // PackageGenerator.MakeColumnIdentifierResolver's own doc comment.
        var leftPropertyInits = string.Join(", ", leftLiterals.Select(kv => $"{PackageGenerator.SanitizeIdentifier(kv.Key)} = {kv.Value.RawLiteral}"));
        var rightPropertyInits = string.Join(", ", rightLiterals.Select(kv => $"{PackageGenerator.SanitizeIdentifier(kv.Key)} = {kv.Value.RawLiteral}"));
        var combinedIdentifierOf = PackageGenerator.MakeColumnIdentifierResolver();
        var combinedIdentifiers = testColumns.ToDictionary(c => c, c => combinedIdentifierOf(c.Name));

        var matchedAssertions = new List<string>
        {
            $"        Assert.Equal({leftLiterals[leftKeyTest.RawColumnName].ExpectedLiteral}, {mapperClassName}.LeftKey(left));",
            $"        Assert.Equal({rightLiterals[rightKeyTest.RawColumnName].ExpectedLiteral}, {mapperClassName}.RightKey(right));",
        };
        foreach (var col in testColumns)
        {
            var literals = col.MayBeAbsent ? rightLiterals : leftLiterals;
            matchedAssertions.Add($"        Assert.Equal({literals[col.RawColumnName].ExpectedLiteral}, matched.{combinedIdentifiers[col]});");
        }

        var rightSideColumns = testColumns.Where(c => c.MayBeAbsent).ToList();

        var usingNamespaces = new List<string> { leftRowTypeNamespace, rightRowTypeNamespace, mappingNamespace }.Distinct();
        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test for {mapperClassName}, proving its",
            "// LeftKey/RightKey selectors and its Map projection produce the expected values for both a",
            "// matched pair and an unmatched left row, with no IUnitOfWork/database involved (a pure",
            "// static-function test). Regenerating this file freely discards any hand edits -- move",
            "// those into a second file instead.",
            "// </auto-generated>",
            "#nullable enable",
        };
        lines.AddRange(usingNamespaces.Select(ns => $"using {ns};"));
        lines.Add("using Xunit;");
        lines.Add("");
        lines.Add($"namespace {testNamespace};");
        lines.Add("");
        lines.Add($"public class {mapperClassName}Tests");
        lines.Add("{");
        lines.Add("    [Fact]");
        lines.Add("    public void Map_ComputesExpectedOutput_ForAMatchedPair()");
        lines.Add("    {");
        lines.Add($"        var left = new {leftRowTypeName} {{ {leftPropertyInits} }};");
        lines.Add($"        var right = new {rightRowTypeName} {{ {rightPropertyInits} }};");
        lines.Add("");
        lines.Add($"        var matched = {mapperClassName}.Map(left, right);");
        lines.Add("");
        lines.AddRange(matchedAssertions);
        lines.Add("    }");

        if (rightSideColumns.Count > 0)
        {
            lines.Add("");
            lines.Add("    [Fact]");
            lines.Add("    public void Map_LeavesRightSideColumnsNull_ForAnUnmatchedLeftRow()");
            lines.Add("    {");
            lines.Add($"        var left = new {leftRowTypeName} {{ {leftPropertyInits} }};");
            lines.Add("");
            lines.Add($"        var unmatched = {mapperClassName}.Map(left, null);");
            lines.Add("");
            foreach (var col in testColumns)
            {
                lines.Add(col.MayBeAbsent
                    ? $"        Assert.Null(unmatched.{combinedIdentifiers[col]});"
                    : $"        Assert.Equal({leftLiterals[col.RawColumnName].ExpectedLiteral}, unmatched.{combinedIdentifiers[col]});");
            }
            lines.Add("    }");
        }

        lines.Add("}");

        return new GeneratedFile($"{mapperClassName}Tests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>
    /// "Data Flow Task -- direct invocation" taxonomy row, added 2026-09-07 closing a real gap
    /// found reviewing actual coverage data on two real packages: every OTHER starter test in this
    /// file exercises one ISOLATED piece of a Data Flow Task (its own source, sink, transform,
    /// router, or mapper) -- nothing calls the real wiring that puts source, transform, and sink
    /// TOGETHER, except <c>RunAsyncTests.cs</c>'s own happy-path test, which many real packages
    /// never even get (a Lookup or an Excel source excludes the whole package from
    /// <c>PackageClassEmitter.SupportsFakeHappyPath</c> entirely).
    ///
    /// <b>Does NOT call the generated <c>DFT_X(uow, ct)</c> method directly -- a real bug caught
    /// building this, not shipped.</b> That method reads a private <c>_load</c> field populated
    /// only by the package's own top-level <c>RunAsync()</c>; calling <c>DFT_X</c> any other way
    /// leaves it null, and <see cref="Etl.Core.Pipeline.DataFlowStep{TRow,TEntity}"/>'s own
    /// <c>RunAsync</c> dereferences <c>load.StartedAtUtc</c> unconditionally -- confirmed by
    /// actually running the first version of this test against a real generated project and
    /// getting a <c>NullReferenceException</c>, not by reasoning about it. Instead this
    /// reconstructs a FRESH <see cref="Etl.Core.Pipeline.DataFlowStep{TRow,TEntity}"/> from the
    /// same already-public pieces the existing Source/Sink/Transform tests already call directly
    /// (<c>package.{sourceMethodName}(...)</c>, <c>new {TransformClassName}()</c>,
    /// <c>package.{sinkMethodName}()</c>) and supplies its OWN real
    /// <see cref="Etl.Core.Abstractions.LoadContext"/> -- proving the same composition the real
    /// package uses, without needing any package-private state.
    ///
    /// <paramref name="needsIntegrationTag"/> is resolved by the caller
    /// (<c>PackageGenerator.RequiresIntegrationForDirectInvocation</c>) from the flow's own
    /// resolved <see cref="FlowSourceSpec"/> -- true whenever any leaf source is SQL/Excel-typed
    /// (no synthetic Tier-A fallback exists for either), in which case the harness is built with
    /// its DEFAULT constructor (real <c>TestData/</c>, real server) instead of the
    /// <c>useSampleDataForFileSources: true</c> override every other CSV/fixed-width-only flow
    /// gets, so this passes with zero fills immediately after generate.
    ///
    /// Deliberately scoped to single-destination flows only -- Conditional Split gets its own
    /// <see cref="EmitConditionalSplitDataFlowTest"/>; Multicast, Merge Join/Union as an OUTER
    /// flow, and a ForEach-Data-Flow-Loop's own per-iteration flow are a named, deliberate
    /// limitation, not a silent one (no real evidenced need to close them yet). A flow whose
    /// source reads a Lookup reference cache is not routed here at all -- see the caller's own
    /// <c>DataFlowTest</c> gap for why that shape can never be called directly at all, by any
    /// construction.
    /// </summary>
    public static GeneratedFile EmitDataFlowStepTest(
        string testNamespace, string rootNamespace, string taskName,
        string sourceMethodName, bool sourceNeedsUow, string rowTypeNamespace, string rowTypeName,
        string transformClassName, string sinkMethodName, string entityNamespace, string entityName,
        bool needsIntegrationTag)
    {
        // taskName is the raw SSIS task display name (free text) -- sanitized for the class/
        // method/file-name positions below; every "{taskName}" string literal further down (the
        // reconstructed step's own runtime label) is still built from the ORIGINAL name, since
        // this test never calls into the package class directly (see this method's own doc
        // comment) and so has no need to match any generated identifier.
        var safeTaskName = PackageGenerator.SanitizeIdentifier(taskName);
        var sourceArgs = sourceNeedsUow ? "uow" : "";
        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test proving '{taskName}' genuinely",
            "// reads, transforms, and writes at least one row end to end -- reconstructs a fresh",
            "// DataFlowStep from the same source/transform/sink pieces the real package uses (never",
            "// calls the generated step method directly -- see this file's own doc comment for why:",
            "// a private _load field only RunAsync() populates). Regenerating this file freely",
            "// discards any hand edits.",
            "// </auto-generated>",
            "#nullable enable",
            "using System;",
            "using Etl.Core.Abstractions;",
            "using Etl.Core.Pipeline;",
            "using Microsoft.Extensions.Logging.Abstractions;",
            $"using {rowTypeNamespace};",
            $"using {entityNamespace};",
            $"using {rootNamespace}.Mapping;",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {safeTaskName}StepDataFlowTests",
            "{",
            "    [Fact]",
        };
        if (needsIntegrationTag) lines.Add("    [Trait(\"Category\", \"Integration\")]");
        lines.Add($"    public async Task {safeTaskName}_WritesAtLeastOneRow_EndToEnd()");
        lines.Add("    {");
        lines.Add(needsIntegrationTag
            ? "        using var harness = new PackageHarness();"
            : "        using var harness = new PackageHarness(useSampleDataForFileSources: true);");
        lines.Add("        var package = harness.Package();");
        lines.Add("        var uow = harness.NewUnitOfWork();");
        lines.Add("");
        lines.Add($"        var source = package.{sourceMethodName}({sourceArgs});");
        lines.Add($"        var transform = new {transformClassName}();");
        lines.Add($"        var sink = package.{sinkMethodName}();");
        lines.Add($"        var step = new DataFlowStep<{rowTypeName}, {entityName}>(\"{taskName}\", source, transform, sink, NullLogger<DataFlowStep<{rowTypeName}, {entityName}>>.Instance);");
        lines.Add("");
        lines.Add($"        await step.RunAsync(uow, new LoadContext(Guid.NewGuid(), DateTime.UtcNow, \"{taskName}\"), CancellationToken.None);");
        lines.Add("");
        lines.Add("        Assert.NotEmpty(uow.BulkInserts);");
        lines.Add("    }");
        lines.Add("}");

        return new GeneratedFile($"{safeTaskName}StepDataFlowTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>
    /// The Conditional-Split shape of <see cref="EmitDataFlowStepTest"/> -- reconstructs a fresh
    /// <see cref="Etl.Core.Pipeline.ConditionalSplitStep{TRow}"/> from the same pieces the real
    /// package uses: <c>package.{sourceMethodName}(...)</c>, <c>new {RouterClassName}()</c>, and
    /// one <see cref="Etl.Core.Pipeline.ConditionalSplitBranch{TRow,TEntity}"/> per branch. Unlike
    /// a single-destination flow, a Conditional Split branch's own <c>SqlBulkSink&lt;TEntity&gt;</c>
    /// is constructed INLINE inside the generated <c>DFT_X()</c> method, with no equivalent
    /// <c>package.{Entity}Destination()</c> method of its own to call -- so this reconstructs one
    /// directly via <c>package.Opt&lt;BulkCopyOptions&gt;()</c>, which is why that method (and
    /// <c>Log&lt;T&gt;</c> alongside it) was widened from <c>private</c> to <c>internal</c> on the
    /// generated package class specifically to support this.
    /// </summary>
    public static GeneratedFile EmitConditionalSplitDataFlowTest(
        string testNamespace, string rootNamespace, string taskName,
        string sourceMethodName, bool sourceNeedsUow, string rowTypeNamespace, string rowTypeName,
        string routerClassName, IReadOnlyList<(string OutputName, string TransformClassName, string EntityName)> branches,
        string entityNamespace, bool needsIntegrationTag)
    {
        // See EmitDataFlowStepTest's own comment -- taskName is free text, sanitized for the
        // identifier positions only; every "{taskName}" runtime label below stays raw.
        var safeTaskName = PackageGenerator.SanitizeIdentifier(taskName);
        var sourceArgs = sourceNeedsUow ? "uow" : "";
        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a STARTER unit test proving '{taskName}' genuinely",
            "// reads, routes, transforms, and writes at least one row end to end, across at least",
            "// one branch -- reconstructs a fresh ConditionalSplitStep from the same source/router/",
            "// branch pieces the real package uses. Regenerating this file freely discards any hand",
            "// edits.",
            "// </auto-generated>",
            "#nullable enable",
            "using System;",
            "using System.Collections.Generic;",
            "using Etl.Core.Abstractions;",
            "using Etl.Core.Data;",
            "using Etl.Core.Pipeline;",
            "using Microsoft.Extensions.Logging.Abstractions;",
            $"using {rowTypeNamespace};",
            $"using {entityNamespace};",
            $"using {rootNamespace}.Mapping;",
            $"using {rootNamespace}.TestDoubles;",
            "using Xunit;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {safeTaskName}StepDataFlowTests",
            "{",
            "    [Fact]",
        };
        if (needsIntegrationTag) lines.Add("    [Trait(\"Category\", \"Integration\")]");
        lines.Add($"    public async Task {safeTaskName}_WritesAtLeastOneRow_EndToEnd()");
        lines.Add("    {");
        lines.Add(needsIntegrationTag
            ? "        using var harness = new PackageHarness();"
            : "        using var harness = new PackageHarness(useSampleDataForFileSources: true);");
        lines.Add("        var package = harness.Package();");
        lines.Add("        var uow = harness.NewUnitOfWork();");
        lines.Add("");
        lines.Add($"        var source = package.{sourceMethodName}({sourceArgs});");
        lines.Add($"        var branches = new List<IConditionalSplitBranch<{rowTypeName}>>");
        lines.Add("        {");
        for (var i = 0; i < branches.Count; i++)
        {
            var b = branches[i];
            var comma = i < branches.Count - 1 ? "," : "";
            lines.Add($"            new ConditionalSplitBranch<{rowTypeName}, {b.EntityName}>(\"{b.OutputName}\", new {b.TransformClassName}(), new SqlBulkSink<{b.EntityName}>(package.Opt<BulkCopyOptions>(), NullLogger<SqlBulkSink<{b.EntityName}>>.Instance)){comma}");
        }
        lines.Add("        };");
        lines.Add($"        var step = new ConditionalSplitStep<{rowTypeName}>(\"{taskName}\", source, new {routerClassName}(), branches, NullLogger<ConditionalSplitStep<{rowTypeName}>>.Instance);");
        lines.Add("");
        lines.Add($"        await step.RunAsync(uow, new LoadContext(Guid.NewGuid(), DateTime.UtcNow, \"{taskName}\"), CancellationToken.None);");
        lines.Add("");
        lines.Add("        Assert.NotEmpty(uow.BulkInserts);");
        lines.Add("    }");
        lines.Add("}");

        return new GeneratedFile($"{safeTaskName}StepDataFlowTests.cs", Rendering.JoinLines(lines));
    }
}
