using Ssis.Extract.Dtsx;
using Ssis.Extract.Model.Pipeline;

namespace Ssis.Extract.Codegen;

/// <summary>One Data Flow Task's own pipeline, carried through just far enough for
/// <see cref="PackageReadmeEmitter"/> to render its per-component detail table via the same
/// <see cref="PipelineFlowOrder"/>/<see cref="ComponentInsight"/> functions the SsisValidationKit
/// walkthrough and <see cref="PackageClassEmitter"/>'s own method ordering already read -- so a
/// walkthrough Seq, a README Seq, and a generated method's own position mean the same thing
/// everywhere they appear.</summary>
public sealed record ReadmeFlowSection(string TaskName, PipelineSpec Pipeline);

public sealed record ReadmeRequest(
    string PackageName,
    IReadOnlyList<ProgramStep> Steps,
    IReadOnlyList<ComponentMethodEntry> MethodInventory,
    IReadOnlyList<ReadmeFlowSection> Flows,
    IReadOnlyList<GeneratedFile> TestFiles,
    IReadOnlyList<TestCoverageNote> TestCoverageNotes,
    IReadOnlyList<GenerationGap> Gaps);

/// <summary>
/// Emits <c>generate/&lt;Package&gt;/README.md</c> -- the primary token-saving artifact for a
/// GitHub-Copilot-only client environment (see <c>Docs/Generated-Tests-Plan.md</c>'s own
/// context): the one file an assistant should read before opening <c>{Package}.cs</c> top to
/// bottom, since it already carries every generated method's own full signature, which control-
/// flow task produced it, and where its test (if any) and gap (if any) live.
///
/// Placed inside the package directory for the same reason <c>HOW-TO-FILL-GAPS.md</c> sits at
/// <c>--out</c> root: whoever opens <c>Generated.slnx</c> directly must find it without
/// <c>Tools/</c> in view.
///
/// <see cref="ReadmeRequest.Steps"/> and the "Step"-kind entries of
/// <see cref="ReadmeRequest.MethodInventory"/> come from the exact same per-step emission pass in
/// <see cref="PackageClassEmitter"/> (one <c>EmitStepMethod</c> call per <see cref="ProgramStep"/>,
/// in the same order) -- zipping them index-for-index is therefore exact correspondence, not a
/// name-based guess. Re-deriving the generated method NAME here independently (e.g. by re-running
/// <c>Reserve</c>'s own collision-avoidance logic a second time) would risk silently drifting from
/// what <c>PackageClassEmitter</c> actually wrote the moment two components share a default SSIS
/// name -- exactly the class of bug this project has been burned by more than once, which is why
/// this emitter never does that.
/// </summary>
public static class PackageReadmeEmitter
{
    public static GeneratedFile Emit(ReadmeRequest request)
    {
        var lines = new List<string>();
        void Line(string text = "") => lines.Add(text);

        Line($"# {request.PackageName}");
        Line();
        Line($"Generated by `ssisx generate` from `{request.PackageName}.dtsx`. Regenerated every run --");
        Line("hand edits to this file are discarded; a Tier-1/2 fill belongs under `fills/`" +
             " (see `HOW-TO-FILL-GAPS.md` at the `--out` root), never in this file.");
        Line();
        Line("**Generated code here is never verified against a real database or real data in this");
        Line("environment.** `dotnet build` proves it compiles; `dotnet test --filter");
        Line("Category!=Integration` proves the starter tests pass against fakes (`TestDoubles/`, no");
        Line("SQL Server involved). Neither proves the SQL/business logic is correct against a real");
        Line("target -- that needs a human, or an `Integration`-tagged run with real connectivity.");
        Line();

        Line("## Control flow");
        Line();
        Line("Seq follows real execution order (the same topological order the generated `RunAsync`");
        Line("calls these methods in). \"Concurrency\" names a wave of steps SSIS ran with no ordering");
        Line("constraint between them -- each such wave runs via `Task.WhenAll`, each branch in its own");
        Line("transaction (see `{Package}.cs`'s own `RunBranchAsync`).");
        Line();
        Line("| Seq | SSIS task | Container | Concurrency | Generated method (full signature) | Test | Gap |");
        Line("|---|---|---|---|---|---|---|");

        var stepEntries = request.MethodInventory.Where(e => e.Kind == "Step").ToList();
        for (var i = 0; i < request.Steps.Count && i < stepEntries.Count; i++)
        {
            var step = request.Steps[i];
            var entry = stepEntries[i];
            var container = step.ContainerPath.Count == 0 ? "_(root)_" : string.Join(" > ", step.ContainerPath.Select(EscapeCell));
            Line($"| {i + 1} | {EscapeCell(entry.SsisName)} | {container} | {ConcurrencyNote(request.Steps, step)} | `{entry.Signature}` | {FindTest(request.TestFiles, request.TestCoverageNotes, entry.MethodName)} | {FindGap(request.Gaps, entry.SsisName)} |");
        }
        Line();

        if (request.Flows.Count > 0)
        {
            Line("## Data flow detail");
            Line();
            Line("Per Data Flow Task, every pipeline component in real data-flow order");
            Line("(`Ssis.Extract.Dtsx.PipelineFlowOrder`), with what it does");
            Line("(`Ssis.Extract.Dtsx.ComponentInsight.Describe`) -- the same two functions the");
            Line("SsisValidationKit walkthrough reads, so a Seq number here means the same thing there.");
            Line("A component folded straight into a transform (Derived Column, Data Conversion, Sort,");
            Line("Union All, Row Count) has no generated method of its own -- it contributes to whichever");
            Line("source/sink method's own row-mapping logic consumes it, not a separate row here.");
            Line();
            foreach (var flow in request.Flows)
            {
                Line($"### {flow.TaskName}");
                Line();
                var order = PipelineFlowOrder.Compute(flow.Pipeline);
                var byId = flow.Pipeline.Components.ToDictionary(c => c.RefId);
                Line("| Seq | Component | Type | What it does |");
                Line("|---|---|---|---|");
                foreach (var refId in order.OrderedComponentRefIds)
                {
                    var comp = byId[refId];
                    Line($"| {order.LevelByRefId[refId]} | {EscapeCell(comp.Name)} | {EscapeCell(comp.ComponentClassId)} | {EscapeCell(ComponentInsight.Describe(comp))} |");
                }
                Line();
            }
        }

        var componentEntries = request.MethodInventory.Where(e => e.Kind is "Source" or "Sink").ToList();
        if (componentEntries.Count > 0)
        {
            Line("## Data flow sources and sinks");
            Line();
            Line("Each Data Flow Task's own source/sink methods, constructed directly inside the step");
            Line("method above that calls them -- no DI factory indirection between where a thing is");
            Line("registered and where it runs.");
            Line();
            Line("| Kind | SSIS component / entity | Generated method (full signature) |");
            Line("|---|---|---|");
            foreach (var e in componentEntries)
                Line($"| {e.Kind} | {EscapeCell(e.SsisName)} | `{e.Signature}` |");
            Line();
        }

        if (request.TestCoverageNotes.Count > 0)
        {
            // Purely additive to the "Control flow" table's own Test column above -- see
            // Docs/AI-Test-Enrichment-Plan.md's own Decision 2: never a gap, never read by
            // PortfolioDigest. Seq is resolved the SAME way FindTest resolves a Step's own test
            // (RelativePath reached via the exact prefix match, not a re-derived name), so a
            // "—" here genuinely means "not tied to one Step" (a Source/Sink/Container/Router/
            // etc. test), not a broken join.
            var seqByRelativePath = new Dictionary<string, int>();
            for (var i = 0; i < stepEntries.Count; i++)
            {
                var methodName = stepEntries[i].MethodName;
                foreach (var f in request.TestFiles)
                    if (Path.GetFileName(f.RelativePath).StartsWith(methodName, StringComparison.Ordinal))
                        seqByRelativePath.TryAdd(f.RelativePath, i + 1);
            }

            Line("## Test coverage notes");
            Line();
            Line("Read this before adding a test -- it says what each existing test already asserts, so a");
            Line("new test adds real coverage instead of duplicating what's here. Additional tests go under");
            Line("`fills/<Package>/MoreTests/` and are applied with `ssisx apply-tests` -- see");
            Line("`HOW-TO-FILL-GAPS.md` at the `--out` root. **This is NOT a gap** -- the package is already");
            Line("fully generatable without it.");
            Line();
            Line("| Seq | Test | Kind | What's already asserted |");
            Line("|---|---|---|---|");
            foreach (var note in request.TestCoverageNotes)
            {
                var seq = seqByRelativePath.TryGetValue(note.RelativePath, out var s) ? s.ToString() : "—";
                Line($"| {seq} | `{EscapeCell(Path.GetFileName(note.RelativePath))}` | {EscapeCell(note.Kind)} | {EscapeCell(note.Summary)} |");
            }
            Line();
        }

        Line("## Where things live");
        Line();
        Line("- `TestDoubles/` (in `{Package}.Tests/`) -- `FakeUnitOfWork`/`RecordingNotifier`/");
        Line("  `PackageHarness`, generated fresh for this package. No SQL Server involved:");
        Line("  `dotnet test --filter Category!=Integration` never opens a real connection.");
        Line("- `gaps/<Package>/` (under `--out` root) -- one self-contained work packet per Tier-1/2");
        Line("  gap this package reported; `gaps.json` is the index.");
        Line("- `fills/`/`fills-library/` -- human-authored answers, never written by `ssisx`; applied");
        Line("  via `ssisx apply-fills`.");
        Line("- `appsettings.Development.json` + `TestData/` -- a package-relative sample-data override");
        Line("  for local `dotnet run` (`DOTNET_ENVIRONMENT=Development`); `TestData/` is empty until a");
        Line("  `LOCAL-DATA` fill supplies real files.");
        Line();

        if (request.Gaps.Count > 0)
        {
            Line("## Gaps reported for this package");
            Line();
            Line("| Location | Reason | Blocking |");
            Line("|---|---|---|");
            foreach (var g in request.Gaps)
                Line($"| {EscapeCell(g.Location)} | {EscapeCell(g.Reason)} | {(g.IsBlocking ? "yes" : "no")} |");
            Line();
        }

        return new GeneratedFile("README.md", Rendering.JoinLines(lines));
    }

    private static string ConcurrencyNote(IReadOnlyList<ProgramStep> steps, ProgramStep step)
    {
        var siblings = steps.Count(s => s.Wave == step.Wave && s.ContainerPath.SequenceEqual(step.ContainerPath));
        return siblings > 1 ? $"wave {step.Wave} (concurrent, {siblings} branches)" : $"wave {step.Wave}";
    }

    private static string FindTest(IReadOnlyList<GeneratedFile> testFiles, IReadOnlyList<TestCoverageNote> testCoverageNotes, string methodName)
    {
        var matches = testFiles
            .Where(f => Path.GetFileName(f.RelativePath).StartsWith(methodName, StringComparison.Ordinal))
            .ToList();
        if (matches.Count == 0) return "_none_";
        var noteByRelativePath = testCoverageNotes.ToDictionary(n => n.RelativePath);
        return string.Join(", ", matches.Select(f =>
        {
            var name = Path.GetFileName(f.RelativePath);
            return noteByRelativePath.TryGetValue(f.RelativePath, out var note)
                ? $"`{name}` -- {EscapeCell(note.Kind)}: {EscapeCell(note.Summary)}"
                : $"`{name}`";
        }));
    }

    private static string FindGap(IReadOnlyList<GenerationGap> gaps, string ssisName)
    {
        var matches = gaps.Where(g => g.Location.Contains(ssisName, StringComparison.Ordinal)).Select(g => g.Reason).ToList();
        return matches.Count == 0 ? "" : EscapeCell(string.Join("; ", matches));
    }

    /// <summary>A Markdown table cell breaks on an embedded "|" or a literal newline -- both show
    /// up for real here (a multi-line SQL statement's own gap reason, a container name containing
    /// no such character today but not guaranteed never to).</summary>
    private static string EscapeCell(string text) =>
        text.Replace("\r", " ").Replace("\n", " ").Replace("|", "\\|");
}
