namespace Ssis.Extract.Codegen;

/// <summary>
/// Emits <c>{Package}.Tests/RunAsyncTests.cs</c> -- the one generated test the taxonomy table
/// (<c>Docs/Generated-Tests-Plan.md</c>) marks "always emittable", regardless of a package's own
/// shape. For most packages the fault is injected at <c>GetBindTokenAsync</c> specifically: every
/// generated <c>RunAsync</c> calls it, unconditionally, as the first statement inside its own
/// <c>try</c> block after BeginAsync succeeds (see <c>PackageClassEmitter</c>'s own emitted
/// bootstrap) -- so that test needs no real file, no real row, and no knowledge of which step a
/// package happens to have first. A Lookup-bearing package is the one real exception: its own
/// reference-table preload runs even earlier, before BeginAsync, and always fails for real against
/// PackageHarness's deliberately-unreachable connection string (LookupCache.LoadAsync takes a raw
/// connection string, never IUnitOfWork, so nothing can fake it) -- that failure is what such a
/// package's test exercises instead, and its assertions differ accordingly (see this class's own
/// <c>Emit</c> method and its <c>usesLookupPreload</c> parameter). Either way this is generatable
/// from nothing but the package's own name and shape, unlike every other row in the taxonomy
/// table, which needs the package's own real shape (a row count, a statement's own SQL text, ...).
/// </summary>
public static class RunAsyncFailureTestEmitter
{
    /// <param name="supportsHappyPath">See <c>PackageClassEmitter.Emit</c>'s own
    /// <c>supportsFakeHappyPath</c> out parameter -- true only when every source/step in this
    /// package is one FakeUnitOfWork/PackageHarness can fully fake with no real connectivity at
    /// all, which is what makes a genuine, whole-package, no-database RunAsync happy-path
    /// assertion meaningful rather than a coin flip on whichever component happens to need a
    /// real server.</param>
    /// <param name="usesLookupPreload">See <c>PackageClassEmitter.Emit</c>'s own parameter of the
    /// same name -- when true, this package's own Lookup reference-table preload runs FIRST inside
    /// RunAsync's try block, before BeginAsync, and always fails for real against PackageHarness's
    /// deliberately-unreachable fake connection string (see TestDoublesEmitter's own
    /// ConnectTimeoutSeconds=1 comment). That real failure -- not a ThrowOnGetBindToken fault
    /// injection, which such a package's RunAsync never even reaches -- is what this test exercises,
    /// and it means BeginAsync itself never ran, so nothing was ever rolled back.</param>
    public static GeneratedFile Emit(
        string rootNamespace, string packageClassName, bool hasFailureHandlers, bool supportsHappyPath, bool usesLookupPreload)
    {
        var lines = new List<string>
        {
            "// <auto-generated>",
            "// Generated by `ssisx generate` -- starter tests proving RunAsync's own failure path",
            "// (rollback, failure handlers if any, a Succeeded=false notification) and, where this",
            "// package's own shape allows it with no real connectivity, its happy path too, all",
            "// without a real database. Regenerating this file freely discards any hand edits.",
            "// </auto-generated>",
            "#nullable enable",
            "using Etl.Core.Hosting;",
            "using Xunit;",
            $"using {rootNamespace}.TestDoubles;",
            "",
            $"namespace {rootNamespace}.Tests;",
            "",
            "public class RunAsyncTests",
            "{",
            "    [Fact]",
        };

        if (usesLookupPreload)
        {
            lines.Add("    public async Task RunAsync_RollsBackAndNotifiesFailure_WhenTheRunCannotStart()");
            lines.Add("    {");
            lines.Add("        // No ThrowOnGetBindToken here -- this package's own Lookup reference-table preload");
            lines.Add("        // runs before BeginAsync (see {Package}.cs's own bootstrap) and always fails for");
            lines.Add("        // real against PackageHarness's deliberately-unreachable fake connection string,");
            lines.Add("        // so that real failure is the fault this test exercises, not an injected one.");
            lines.Add("        using var harness = new PackageHarness();");
            lines.Add("        var package = harness.Package();");
            lines.Add("");
            lines.Add("        var exitCode = await package.RunAsync(CancellationToken.None);");
            lines.Add("");
            lines.Add("        Assert.Equal(ExitCode.LoadFailed, exitCode);");
            lines.Add("        var uow = Assert.Single(harness.CreatedUnitsOfWork);");
            lines.Add("        // BeginAsync never ran (the Lookup preload failed before reaching it), so there is");
            lines.Add("        // no transaction to roll back -- see PackageClassEmitter's own uowActive guard.");
            lines.Add("        Assert.False(uow.BeginCalled);");
            lines.Add("        Assert.False(uow.RollbackCalled);");
            lines.Add("        Assert.False(uow.CommitCalled);");
            lines.Add("        Assert.NotNull(harness.Notifier.Result);");
            lines.Add("        Assert.False(harness.Notifier.Result!.Succeeded);");

            if (hasFailureHandlers)
            {
                lines.Add("        // A failure handler is still attempted here even though no transaction was ever");
                lines.Add("        // opened -- ExecuteSqlWithoutTransactionAsync's own precondition only blocks a");
                lines.Add("        // CURRENTLY active transaction, which this state (BeginAsync never reached) is not.");
                lines.Add("        Assert.NotEmpty(uow.ExecutedSqlWithoutTransaction);");
                lines.Add("        Assert.NotEmpty(harness.Notifier.Result!.FailureHandlersRun);");
            }

            lines.Add("    }");
        }
        else
        {
            lines.Add("    public async Task RunAsync_RollsBackAndNotifiesFailure_WhenTheRunCannotStart()");
            lines.Add("    {");
            lines.Add("        using var harness = new PackageHarness();");
            lines.Add("        harness.ThrowOnGetBindToken = new InvalidOperationException(\"synthetic failure injected by RunAsyncTests\");");
            lines.Add("        var package = harness.Package();");
            lines.Add("");
            lines.Add("        var exitCode = await package.RunAsync(CancellationToken.None);");
            lines.Add("");
            lines.Add("        Assert.Equal(ExitCode.LoadFailed, exitCode);");
            lines.Add("        var uow = Assert.Single(harness.CreatedUnitsOfWork);");
            lines.Add("        Assert.True(uow.RollbackCalled);");
            lines.Add("        Assert.False(uow.CommitCalled);");
            lines.Add("        Assert.NotNull(harness.Notifier.Result);");
            lines.Add("        Assert.False(harness.Notifier.Result!.Succeeded);");

            if (hasFailureHandlers)
            {
                lines.Add("        // Nothing reached its own normal position before the fault fired, so every");
                lines.Add("        // failure handler this package declares runs from the catch block -- after the");
                lines.Add("        // rollback (FakeUnitOfWork.ExecuteSqlWithoutTransactionAsync's own precondition),");
                lines.Add("        // never before it.");
                lines.Add("        Assert.NotEmpty(uow.ExecutedSqlWithoutTransaction);");
                lines.Add("        Assert.NotEmpty(harness.Notifier.Result!.FailureHandlersRun);");
            }

            lines.Add("    }");
        }

        if (supportsHappyPath)
        {
            lines.Add("");
            lines.Add("    [Fact]");
            lines.Add("    public async Task RunAsync_Succeeds_AgainstFakesWithNoFaultInjected()");
            lines.Add("    {");
            // useSampleDataForFileSources: true -- this test runs the WHOLE pipeline against fakes,
            // including a real CSV/fixed-width read, so it needs the harness's own Tier-A synthetic
            // sample rather than the real TestData/ file a LOCAL-DATA fill may not have supplied yet
            // (see PackageHarness's own doc comment on this parameter).
            lines.Add("        using var harness = new PackageHarness(useSampleDataForFileSources: true);");
            lines.Add("        var package = harness.Package();");
            lines.Add("");
            lines.Add("        var exitCode = await package.RunAsync(CancellationToken.None);");
            lines.Add("");
            lines.Add("        Assert.Equal(ExitCode.Success, exitCode);");
            lines.Add("        Assert.NotEmpty(harness.CreatedUnitsOfWork);");
            lines.Add("        Assert.All(harness.CreatedUnitsOfWork, uow =>");
            lines.Add("        {");
            lines.Add("            Assert.True(uow.CommitCalled);");
            lines.Add("            Assert.False(uow.RollbackCalled);");
            lines.Add("        });");
            lines.Add("        Assert.NotNull(harness.Notifier.Result);");
            lines.Add("        Assert.True(harness.Notifier.Result!.Succeeded);");
            lines.Add("        Assert.Empty(harness.Notifier.Result!.FailureHandlersRun);");
            lines.Add("    }");
        }

        lines.Add("}");

        return new GeneratedFile("RunAsyncTests.cs", Rendering.JoinLines(lines));
    }
}
