namespace Ssis.Extract.Codegen;

/// <summary>
/// Emitter rewrite phase 5 (<c>Docs/Emitter-Rewrite-Plan.md</c> §8c): a starter xUnit test per
/// Execute SQL Task, the smallest and cheapest slice of "every component gets its own testable
/// unit" -- <see cref="SqlStatementBuilderEmitter"/>'s own <c>BuildStatement()</c> is already a
/// pure, dependency-free static method (the SQL text is a literal known in full at generation
/// time, no database or file needed), so asserting it needs no oracle, no fixture, and no
/// "Category=Integration" trait the way a source/sink test touching a real file or database
/// would. Deliberately scoped to the non-parameterized case only (an ordinary post-flow/secondary-
/// connection Execute SQL Task) -- a ForEach Loop's own per-iteration <c>BuildStatement(currentFile)</c>
/// is a genuinely different shape (its expected text depends on re-deriving the same string-concat
/// translation <see cref="ForEachLoopEmitter"/> already performed, which risks silently drifting
/// from what that translator actually does) and is left for a human to assert by hand, same as
/// this tool's every other stated pilot-scope boundary.
/// </summary>
public static class SqlStatementTestEmitter
{
    public static GeneratedFile Emit(string testNamespace, string mappingNamespace, string taskName, string sql)
    {
        var statementClassName = taskName + "Statement";
        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a starter unit test for {statementClassName}, asserting",
            "// the exact statement text this Execute SQL Task's own .dtsx declared. Regenerating this",
            "// file freely discards any hand edits -- move those into a second file instead.",
            "// </auto-generated>",
            "using Xunit;",
            $"using {mappingNamespace};",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {statementClassName}Tests",
            "{",
            "    [Fact]",
            "    public void BuildStatement_EmitsTheStatementTheDtsxDeclared() =>",
            $"        Assert.Equal({ProgramEmitter.CSharpStringLiteral(sql)}, {statementClassName}.BuildStatement());",
            "}",
        };

        return new GeneratedFile($"{statementClassName}Tests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>
    /// A second, STEP-LEVEL starter test alongside <see cref="Emit"/>'s own statement-text test --
    /// calls the generated <c>{Package}Package.{TaskName}(uow, ct)</c> method directly (visible via
    /// <c>InternalsVisibleTo</c>) with a standalone <see cref="TestDoublesEmitter"/>-emitted
    /// <c>FakeUnitOfWork</c>, and asserts the statement actually reached
    /// <c>IUnitOfWork.ExecuteSqlAsync</c> -- the taxonomy table's own "Execute SQL Task" row asks
    /// for both: the statement class in isolation (<see cref="Emit"/>) AND the method that runs it
    /// inside the shared transaction (this one). Deliberately scoped to an ORDINARY
    /// <see cref="ProgramSqlStep"/> only -- a <c>ProgramSecondaryConnectionSqlStep</c> opens its own
    /// real <c>SqlConnection</c> unconditionally (see that Etl.Core type's own doc comment), so it
    /// cannot be exercised against THIS assertion (the statement reaching the shared transaction --
    /// a secondary-connection step never touches it at all); see
    /// <see cref="EmitSecondaryConnectionStepTest"/> for that shape's own starter test instead.
    /// </summary>
    public static GeneratedFile EmitStepTest(string testNamespace, string rootNamespace, string taskName)
    {
        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a starter unit test for {taskName}, asserting the",
            "// statement actually reaches the shared transaction when this step runs. Regenerating this",
            "// file freely discards any hand edits -- move those into a second file instead.",
            "// </auto-generated>",
            "using Xunit;",
            $"using {rootNamespace}.Mapping;",
            $"using {rootNamespace}.TestDoubles;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {taskName}StepTests",
            "{",
            "    [Fact]",
            $"    public async Task {taskName}_ExecutesTheStatementInsideTheSharedTransaction()",
            "    {",
            "        using var harness = new PackageHarness();",
            "        var package = harness.Package();",
            "        var uow = harness.NewUnitOfWork();",
            "",
            $"        await package.{taskName}(uow, CancellationToken.None);",
            "",
            $"        Assert.Contains({taskName}Statement.BuildStatement(), uow.ExecutedSql);",
            "    }",
            "}",
        };

        return new GeneratedFile($"{taskName}StepTests.cs", Rendering.JoinLines(lines));
    }

    /// <summary>
    /// "Secondary-connection SQL" taxonomy row (<c>Docs/Generated-Tests-Plan.md</c>) -- the
    /// <see cref="EmitStepTest"/> sibling for a <c>ProgramSecondaryConnectionSqlStep</c>, which
    /// opens its own independent <c>SqlConnection</c> and never touches the <c>IUnitOfWork</c>
    /// passed to it at all (see that Etl.Core type's own doc comment). Mirrors
    /// <c>D:\PoC\SSIS_Rewrite\tests\Etl.Core.Tests\Pipeline\SecondaryConnectionSqlStepTests.cs</c>'s
    /// own <c>RunAsync_NeverTouchesTheUnitOfWork</c> exactly, at the PACKAGE level: proving this
    /// generated method's own wiring (the right connection-manager name, the right statement) --
    /// not re-proving the underlying Etl.Core class's behaviour, already covered once for the
    /// whole portfolio.
    ///
    /// <para>Needs no real server and no <c>[Trait("Category", "Integration")]</c> tag at all --
    /// <see cref="TestDoublesEmitter"/>'s own <c>PackageHarness</c> wires
    /// <c>SecondaryConnections:{cm}</c> at a deliberately UNREACHABLE local instance name (fails
    /// fast, no DNS/network round trip), so the connection attempt itself always throws a real
    /// <c>SqlException</c> -- which is exactly the evidence needed that the passed-in
    /// <c>IUnitOfWork</c> was never touched, the same as the mirrored Etl.Core.Tests test.</para>
    /// </summary>
    public static GeneratedFile EmitSecondaryConnectionStepTest(string testNamespace, string rootNamespace, string taskName)
    {
        var lines = new List<string>
        {
            "// <auto-generated>",
            $"// Generated by `ssisx generate` -- a starter unit test for {taskName}, asserting it opens",
            "// its own connection and never touches the shared IUnitOfWork at all. Regenerating this",
            "// file freely discards any hand edits -- move those into a second file instead.",
            "// </auto-generated>",
            "using Microsoft.Data.SqlClient;",
            "using Xunit;",
            $"using {rootNamespace}.TestDoubles;",
            "",
            $"namespace {testNamespace};",
            "",
            $"public class {taskName}StepTests",
            "{",
            "    [Fact]",
            $"    public async Task {taskName}_NeverTouchesTheSharedUnitOfWork()",
            "    {",
            "        using var harness = new PackageHarness();",
            "        var package = harness.Package();",
            "        var uow = harness.NewUnitOfWork();",
            "",
            $"        await Assert.ThrowsAsync<SqlException>(() => package.{taskName}(uow, CancellationToken.None));",
            "",
            "        Assert.Empty(uow.ExecutedSql);",
            "        Assert.Empty(uow.ExecutedParameterizedSql);",
            "        Assert.False(uow.BeginCalled);",
            "    }",
            "}",
        };

        return new GeneratedFile($"{taskName}StepTests.cs", Rendering.JoinLines(lines));
    }
}
