<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ssis.Extract.Model\Ssis.Extract.Model.csproj" />
    <ProjectReference Include="..\Ssis.Extract.Dtsx\Ssis.Extract.Dtsx.csproj" />
    <ProjectReference Include="..\Ssis.Runtime.Expressions\Ssis.Runtime.Expressions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ssis.Extract.Codegen.Tests" />
  </ItemGroup>

</Project>
