namespace Ssis.Extract.Codegen;

/// <summary>
/// Emits <c>{Package}.Tests/TestDoubles/{FakeUnitOfWork,RecordingNotifier,PackageHarness}.cs</c> --
/// the "Foundation" phase of the generated-tests plan (<c>Docs/Generated-Tests-Plan.md</c>).
///
/// <c>FakeUnitOfWork</c>/<c>RecordingNotifier</c> exist today only inside the hand-written
/// <c>Etl.Core.Tests</c> project (a dev-repo test project this generator never ships). Rather than
/// add a new <c>Etl.Core.Testing</c> library and a flag to carry it into every generated solution,
/// they are emitted per package instead -- the same pattern <c>SsisFnEmitter</c> already uses for
/// <c>Ssis/SsisFn.cs</c> (self-contained, disposable, generated fresh, no new dependency).
/// <c>FakeUnitOfWork</c> is ported byte-for-byte in spirit from
/// <c>D:\PoC\SSIS_Rewrite\tests\Etl.Core.Tests\TestDoubles\FakeUnitOfWork.cs</c> -- same recorders,
/// same fault injection, same mirrored preconditions (so failure ORDERING can be pinned with no
/// database at all) -- plus one addition that copy does not need: a <c>ThrowOnGetBindToken</c>
/// hook, because a generated <c>RunAsync</c>'s own very first call inside its <c>try</c> block is
/// unconditionally <c>uow.GetBindTokenAsync(ct)</c> (see <c>PackageClassEmitter</c>'s own emitted
/// bootstrap) -- the one universal fault-injection point that is always reachable regardless of a
/// package's own shape (no file, no database row, no specific step needs to exist first), which is
/// exactly what makes the "RunAsync failure path" starter test always emittable.
/// </summary>
public static class TestDoublesEmitter
{
    public static EmitResult Emit(
        string rootNamespace, string packageClassName, string dbContextTypeName,
        IReadOnlyList<(string Key, string FileName)>? testDataFiles = null,
        IReadOnlyList<string>? sinkFileKeys = null,
        IReadOnlyList<string>? fileSystemTaskKeys = null,
        IReadOnlyList<string>? forEachLoopKeys = null,
        IReadOnlyList<string>? secondaryConnectionManagerNames = null,
        IReadOnlyList<(string Key, string FileName)>? sampleDataFallbackFiles = null)
    {
        var ns = $"{rootNamespace}.TestDoubles";
        var files = new List<GeneratedFile>
        {
            new("TestDoubles/FakeUnitOfWork.cs", EmitFakeUnitOfWork(ns)),
            new("TestDoubles/RecordingNotifier.cs", EmitRecordingNotifier(ns)),
            new("TestDoubles/PackageHarness.cs", EmitPackageHarness(rootNamespace, ns, packageClassName, dbContextTypeName, testDataFiles ?? [], sinkFileKeys ?? [], fileSystemTaskKeys ?? [], forEachLoopKeys ?? [], secondaryConnectionManagerNames ?? [], sampleDataFallbackFiles ?? [])),
        };
        return new EmitResult(files, []);
    }

    private static string EmitFakeUnitOfWork(string ns)
    {
        var lines = new List<string>
        {
            "// <auto-generated>",
            "// Generated by `ssisx generate` -- ported from Etl.Core.Tests' own FakeUnitOfWork test double",
            "// (see Tools/Etl.Core). Regenerating this file freely discards any hand edits -- move those",
            "// into a second file instead.",
            "// </auto-generated>",
            // A file recognized as auto-generated (this comment banner is the recognized shape)
            // does not inherit the project's own <Nullable>enable</Nullable> context -- Roslyn
            // requires an explicit directive in the file itself, or every nullable-annotated type
            // below (string?, object?[], ...) is a real CS8669 build error.
            "#nullable enable",
            "using System.Data;",
            "using System.Data.Common;",
            "using Etl.Core.Abstractions;",
            "using Etl.Core.Data;",
            "using Microsoft.EntityFrameworkCore;",
            "",
            $"namespace {ns};",
            "",
            "/// <summary>",
            "/// A fake IUnitOfWork with no database behind it at all -- BeginAsync/CommitAsync/RollbackAsync",
            "/// just flip flags, and BulkInsertAsync drains the reader and records what it was called with",
            "/// instead of touching SqlBulkCopy. This is what lets every generated step be exercised with",
            "/// no SQL Server anywhere in the test run.",
            "/// </summary>",
            "public sealed class FakeUnitOfWork(DbContext context) : IUnitOfWork",
            "{",
            "    public DbContext Context { get; } = context;",
            "",
            "    public bool BeginCalled { get; private set; }",
            "    public bool CommitCalled { get; private set; }",
            "    public bool RollbackCalled { get; private set; }",
            "",
            "    /// <summary>Mirrors the real UnitOfWork's own \"is a transaction currently open\" state --",
            "    /// true only between a successful BeginAsync and its own CommitAsync/RollbackAsync. Kept",
            "    /// separate from BeginCalled/RollbackCalled (which never reset) so ExecuteSqlWithoutTransactionAsync",
            "    /// correctly allows a failure handler to run when BeginAsync was never reached at all -- e.g. a",
            "    /// Lookup preload failing before the transaction opens (see PackageClassEmitter's own bootstrap) --",
            "    /// not just after an explicit RollbackAsync.</summary>",
            "    private bool _transactionActive;",
            "    public List<string> ExecutedSql { get; } = [];",
            "    public List<ParameterizedSqlCall> ExecutedParameterizedSql { get; } = [];",
            "    public List<string> ExecutedSqlWithoutTransaction { get; } = [];",
            "",
            "    /// <summary>When set, a without-transaction statement containing this text throws -- so a",
            "    /// handler failing in isolation can be tested without a database.</summary>",
            "    public string? ThrowOnSqlWithoutTransactionContaining { get; set; }",
            "",
            "    /// <summary>When set, GetBindTokenAsync throws this instead of returning a token -- the one",
            "    /// universal fault-injection point every generated RunAsync reaches unconditionally, right",
            "    /// after BeginAsync, before any step runs (see PackageClassEmitter's own emitted bootstrap).",
            "    /// This is what makes a package-shape-agnostic \"RunAsync failure path\" test possible with no",
            "    /// file or database row needing to exist first.</summary>",
            "    public Exception? ThrowOnGetBindToken { get; set; }",
            "",
            "    public List<BulkInsertCall> BulkInserts { get; } = [];",
            "",
            "    public Task BeginAsync(IsolationLevel level, CancellationToken ct)",
            "    {",
            "        BeginCalled = true;",
            "        _transactionActive = true;",
            "        return Task.CompletedTask;",
            "    }",
            "",
            "    public Task<int> ExecuteSqlAsync(string sql, CancellationToken ct)",
            "    {",
            "        ExecutedSql.Add(sql);",
            "        return Task.FromResult(0);",
            "    }",
            "",
            "    public Task<int> ExecuteSqlAsync(string sql, object?[] parameters, CancellationToken ct)",
            "    {",
            "        ExecutedParameterizedSql.Add(new ParameterizedSqlCall(sql, parameters));",
            "        return Task.FromResult(1);",
            "    }",
            "",
            "    public async Task<long> BulkInsertAsync(",
            "        string destinationTable,",
            "        DbDataReader reader,",
            "        IReadOnlyList<BulkColumnMapping> columnMappings,",
            "        BulkCopyOptions options,",
            "        CancellationToken ct)",
            "    {",
            "        long rowsWritten = 0;",
            "        while (await reader.ReadAsync(ct)) rowsWritten++;",
            "",
            "        BulkInserts.Add(new BulkInsertCall(destinationTable, columnMappings, rowsWritten));",
            "        return rowsWritten;",
            "    }",
            "",
            "    /// <summary>",
            "    /// Mirrors the real UnitOfWork's own precondition rather than just recording the call -- that",
            "    /// is what lets a test prove a failure handler runs AFTER the rollback with no database",
            "    /// involved. A handler that ran first would silently be rolled back in production, so the",
            "    /// ordering is the behaviour worth pinning, not an implementation detail.",
            "    /// </summary>",
            "    public Task<int> ExecuteSqlWithoutTransactionAsync(string sql, CancellationToken ct)",
            "    {",
            "        if (_transactionActive)",
            "            throw new InvalidOperationException(",
            "                \"ExecuteSqlWithoutTransactionAsync was called while a transaction is still active.\");",
            "",
            "        ExecutedSqlWithoutTransaction.Add(sql);",
            "",
            "        if (ThrowOnSqlWithoutTransactionContaining is { } marker && sql.Contains(marker))",
            "            throw new InvalidOperationException($\"fake failure for SQL containing '{marker}'\");",
            "",
            "        return Task.FromResult(1);",
            "    }",
            "",
            "    public int BindTokensIssued { get; private set; }",
            "    private string? _bindToken;",
            "",
            "    /// <summary>Mirrors the real UnitOfWork's own caching -- a fake, plainly-not-a-real-SQL-Server",
            "    /// value the first time, then that same value on every later call, with NO further increment",
            "    /// to BindTokensIssued. Throws ThrowOnGetBindToken instead, when set, BEFORE caching anything --",
            "    /// see that property's own doc comment for why this is the universal failure-injection",
            "    /// point.</summary>",
            "    public Task<string> GetBindTokenAsync(CancellationToken ct)",
            "    {",
            "        if (ThrowOnGetBindToken is { } ex) throw ex;",
            "        if (_bindToken is not null) return Task.FromResult(_bindToken);",
            "",
            "        BindTokensIssued++;",
            "        _bindToken = \"fake-bind-token\";",
            "        return Task.FromResult(_bindToken);",
            "    }",
            "",
            "    public Task CommitAsync(CancellationToken ct)",
            "    {",
            "        CommitCalled = true;",
            "        _transactionActive = false;",
            "        return Task.CompletedTask;",
            "    }",
            "",
            "    public Task RollbackAsync(CancellationToken ct)",
            "    {",
            "        RollbackCalled = true;",
            "        _transactionActive = false;",
            "        return Task.CompletedTask;",
            "    }",
            "",
            "    public ValueTask DisposeAsync() => ValueTask.CompletedTask;",
            "}",
            "",
            "public sealed record BulkInsertCall(string DestinationTable, IReadOnlyList<BulkColumnMapping> ColumnMappings, long RowsWritten);",
            "",
            "public sealed record ParameterizedSqlCall(string Sql, object?[] Parameters);",
        };

        return Rendering.JoinLines(lines);
    }

    private static string EmitRecordingNotifier(string ns)
    {
        var lines = new List<string>
        {
            "// <auto-generated>",
            "// Generated by `ssisx generate`. Regenerating this file freely discards any hand edits.",
            "// </auto-generated>",
            "#nullable enable",
            "using Etl.Core.Abstractions;",
            "using Etl.Core.Notifications;",
            "",
            $"namespace {ns};",
            "",
            "/// <summary>Captures the PackageResult from a harness-driven RunAsync call instead of sending",
            "/// email -- the generated Program.cs never constructs this; only PackageHarness does.</summary>",
            "public sealed class RecordingNotifier : IPackageResultNotifier",
            "{",
            "    public PackageResult? Result { get; private set; }",
            "",
            "    public Task NotifyAsync(PackageResult result, CancellationToken ct)",
            "    {",
            "        Result = result;",
            "        return Task.CompletedTask;",
            "    }",
            "}",
        };

        return Rendering.JoinLines(lines);
    }

    private static string EmitPackageHarness(
        string rootNamespace, string ns, string packageClassName, string dbContextTypeName,
        IReadOnlyList<(string Key, string FileName)> testDataFiles, IReadOnlyList<string> sinkFileKeys,
        IReadOnlyList<string> fileSystemTaskKeys, IReadOnlyList<string> forEachLoopKeys,
        IReadOnlyList<string> secondaryConnectionManagerNames,
        IReadOnlyList<(string Key, string FileName)> sampleDataFallbackFiles)
    {
        const string fakeConnectionString =
            "Server=(local);Database=Fake;Trusted_Connection=True;TrustServerCertificate=True;";
        // Deliberately a NONEXISTENT NAMED INSTANCE on the local machine, not a remote hostname --
        // this fails fast (no DNS lookup, no network round trip) with a genuine SqlException,
        // mirroring D:\PoC\SSIS_Rewrite\tests\Etl.Core.Tests\Pipeline\SecondaryConnectionSqlStepTests.cs's
        // own RunAsync_NeverTouchesTheUnitOfWork exactly -- see ComponentTestEmitter's own
        // "Secondary-connection SQL" test, the one thing this value exists for.
        const string unreachableSecondaryServer = "(local)\\NonexistentInstance12345";

        var lines = new List<string>
        {
            "// <auto-generated>",
            "// Generated by `ssisx generate`. Regenerating this file freely discards any hand edits.",
            "// </auto-generated>",
            "#nullable enable",
            "using System.Collections.Concurrent;",
            "using System.Data;",
            "using Etl.Core.Abstractions;",
            "using Etl.Core.Data;",
            "using Etl.Core.Hosting;",
            "using Etl.Core.Notifications;",
            $"using {rootNamespace}.Model;",
            "using Microsoft.EntityFrameworkCore;",
            "using Microsoft.Extensions.DependencyInjection;",
            "using Microsoft.Extensions.Logging;",
            "using Microsoft.Extensions.Logging.Abstractions;",
            "using Microsoft.Extensions.Options;",
            "",
            $"namespace {ns};",
            "",
            "/// <summary>",
            $"/// Composes a fake-backed ServiceProvider for {packageClassName} -- a fresh FakeUnitOfWork",
            "/// per DI scope (so RunBranchAsync's own per-branch transactions are individually observable",
            "/// -- see {Package}.cs's own concurrent-wave handling), a null logger for every ILogger&lt;T&gt;,",
            "/// a fixed TimeProvider, and empty FileSourceOptions/DatabaseOptions/BulkCopyOptions (populated",
            "/// for real once a testDataFiles entry exists). Every file-based source -- CSV, fixed-width,",
            "/// Excel alike -- resolves through a package-relative TestData/ folder, the SAME folder",
            "/// appsettings.Development.json points a real local run at (see the LOCAL-DATA work packet):",
            "/// there is no separate, tool-synthesized fallback here, so a source's own read test needs",
            "/// its real LOCAL-DATA fill applied before it can pass -- see EmitFileSourceTest's own doc",
            "/// comment. No SQL Server involved anywhere by default: the DbContext",
            $"/// behind each FakeUnitOfWork is the real generated {dbContextTypeName}, configured with a",
            "/// connection string that is NEVER opened -- EF only needs the model to answer schema/column",
            "/// questions (see FakeUnitOfWork.BulkInsertAsync). NewRealUnitOfWorkAsync() is the one",
            "/// deliberate opt-in exception -- see its own doc comment.",
            "/// </summary>",
            // internal, not public -- it constructs and exposes {className} directly (Package()'s
            // own return type), and that generated package class is itself internal (visible to
            // this test project only via InternalsVisibleTo), so a public PackageHarness would be
            // a real CS0050 (a public method cannot expose a less-accessible return type).
            "internal sealed class PackageHarness : IDisposable",
            "{",
            "    private readonly ServiceProvider _root;",
            "",
            "    /// <summary>The SAME DatabaseOptions the fake-backed ServiceProvider above was built",
            "    /// from -- captured so NewRealUnitOfWorkAsync() reads whatever a human has pointed this",
            "    /// at for a local Integration run (see that method's own doc comment) rather than a",
            "    /// second, independent copy that could silently drift from the DI-registered one.</summary>",
            "    private readonly DatabaseOptions _databaseOptions;",
            "",
            "    /// <summary>A fresh, isolated temp folder for this harness instance's own Flat File",
            "    /// Destination writes (a real IBulkSink&lt;T&gt; never touches IUnitOfWork -- see",
            "    /// FlatFileBulkSink's own doc comment -- so there is nothing to fake; writing to a real,",
            "    /// per-instance folder instead is what keeps a \"Sink -- flat file\" starter test isolated",
            "    /// from every other test run, parallel or not). Deleted in Dispose.</summary>",
            "    private readonly string _sinkOutputDirectory = Path.Combine(Path.GetTempPath(), \"ssisx-tests\", Guid.NewGuid().ToString(\"N\"));",
            "",
            "    /// <summary>Every FakeUnitOfWork actually resolved from DI so far -- one per scope, so a",
            "    /// concurrent wave's own per-branch transactions are each independently inspectable after",
            "    /// RunAsync returns. A ConcurrentBag because a concurrent wave resolves more than one",
            "    /// scope's own IUnitOfWork in parallel.</summary>",
            "    public ConcurrentBag<FakeUnitOfWork> CreatedUnitsOfWork { get; } = [];",
            "",
            "    public RecordingNotifier Notifier { get; } = new();",
            "",
            "    /// <summary>Set before calling Package().RunAsync() to make the VERY NEXT",
            "    /// FakeUnitOfWork resolved from DI throw this from GetBindTokenAsync -- the universal,",
            "    /// package-shape-agnostic failure-injection point (see FakeUnitOfWork's own doc",
            "    /// comment). Read at DI-resolution time, not at harness-construction time, so setting",
            "    /// it any time before RunAsync() is called takes effect.</summary>",
            "    public Exception? ThrowOnGetBindToken { get; set; }",
            "",
            "    /// <param name=\"useSampleDataForFileSources\">True ONLY for the happy-path RunAsync",
            "    /// starter test, which runs the WHOLE pipeline (including a real CSV/fixed-width read)",
            "    /// and so needs SOME parseable file even with no LOCAL-DATA fill supplied yet -- points",
            "    /// every CSV/fixed-width source at the Tier-A synthetic sample (SampleData/) instead of",
            "    /// the real TestData/ file. Every OTHER test (the isolated source-read Integration test",
            "    /// included) leaves this false and gets the real TestData/ file, exactly as before.</param>",
            "    public PackageHarness(bool useSampleDataForFileSources = false)",
            "    {",
            "        var services = new ServiceCollection();",
            "        services.AddSingleton(typeof(ILogger<>), typeof(NullLogger<>));",
            "        services.AddSingleton<TimeProvider>(new FixedTimeProvider(new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero)));",
            "        // ConnectTimeoutSeconds=1 -- a Lookup preload (LookupCache.LoadAsync) takes a raw",
            "        // connection string, never IUnitOfWork, so it always attempts a REAL connection to",
            "        // this fake server regardless of anything else being faked; the default 15s timeout",
            "        // would make every Lookup-bearing package's RunAsync failure-path test that slow.",
            "        _databaseOptions = new DatabaseOptions { Server = \"(fake)\", Database = \"Fake\", ConnectTimeoutSeconds = 1 };",
            "        services.AddSingleton<IOptions<DatabaseOptions>>(Options.Create(_databaseOptions));",
            };
        if (secondaryConnectionManagerNames.Count > 0)
        {
            // Only added when actually used -- an unconditional using here would be unused (and
            // so fail the build under TreatWarningsAsErrors=true) for every package with no
            // secondary connection, exactly the trap Docs/Generated-Tests-Plan.md's own
            // Verification section warns about.
            lines.Insert(lines.IndexOf("using Microsoft.EntityFrameworkCore;") + 1, "using Microsoft.Extensions.Configuration;");
            // A SecondaryConnectionSqlStep (or, since Phase 5, 2026-09-17, a cross-database
            // Data Flow SOURCE -- see SqlFlowSource's own doc comment) resolves its own
            // connection string via Config() -- Program.cs's own IConfiguration (appsettings +
            // environment + User Secrets), never IOptions<DatabaseOptions> -- so it needs its OWN
            // registered IConfiguration here, one this test project has no reason to register
            // otherwise. Every connection manager points at unreachableSecondaryServer (see that
            // constant's own comment): the "Secondary -- connection SQL" starter test
            // (ComponentTestEmitter) exists to prove the step never touches the passed-in
            // IUnitOfWork, which is provable from a FAST, deterministic connection FAILURE just as
            // well as a real one -- no live server needed here at all. A cross-database source's
            // own [Trait("Category","Integration")] read test needs a human to point this SAME
            // dictionary at a real server for a local run (Tools/COPILOT_TESTING_GUIDE.md's own
            // "Category=Integration" section) -- only Server/Database/ConnectTimeoutSeconds are
            // wired by default, so TrustServerCertificate/Encrypt/AuthMode need adding too if the
            // real target needs them (confirmed necessary against a self-signed local instance).
            lines.Add("        var secondaryConnectionConfig = new Dictionary<string, string?>");
            lines.Add("        {");
            foreach (var cmName in secondaryConnectionManagerNames)
            {
                lines.Add($"            [\"SecondaryConnections:{cmName}:Server\"] = {ProgramEmitter.CSharpStringLiteral(unreachableSecondaryServer)},");
                lines.Add($"            [\"SecondaryConnections:{cmName}:Database\"] = \"Fake\",");
                lines.Add($"            [\"SecondaryConnections:{cmName}:ConnectTimeoutSeconds\"] = \"1\",");
            }
            lines.Add("        };");
            lines.Add("        services.AddSingleton<IConfiguration>(new ConfigurationBuilder().AddInMemoryCollection(secondaryConnectionConfig).Build());");
        }
        if (testDataFiles.Count == 0 && sinkFileKeys.Count == 0 && fileSystemTaskKeys.Count == 0 && forEachLoopKeys.Count == 0)
        {
            lines.Add("        services.AddSingleton<IOptions<FileSourceOptions>>(Options.Create(new FileSourceOptions()));");
        }
        else
        {
            // _sinkOutputDirectory is created lazily by FlatFileBulkSink itself when a "Sink --
            // flat file" test writes to it (see that type's own doc comment), but neither
            // File.Copy (a "File System Task" starter test's own runtime call) nor the plain
            // File.WriteAllTextAsync that test uses to seed its own source file will create a
            // missing directory -- so it is created eagerly here instead, unconditionally,
            // whenever this branch fires at all (harmless idempotent no-op for a sink/CSV-only
            // package that never reads it before the sink itself creates it).
            lines.Add("        Directory.CreateDirectory(_sinkOutputDirectory);");
            // A ForEach Loop's own folder-only FileSourceEntry (empty SourceFileName -- see
            // PackageGenerator.ResolveForEachFileLoop's own comment) needs a REAL, EMPTY,
            // pre-existing subfolder per key -- Directory.EnumerateFiles throws
            // DirectoryNotFoundException if the loop runs before a test writes anything into it,
            // and a shared flat folder would let two different loops' own test files collide.
            foreach (var key in forEachLoopKeys)
                lines.Add($"        Directory.CreateDirectory(ForEachLoopFolder(\"{key}\"));");
            // Every file-based source this package has (CSV, fixed-width, Excel alike) points at
            // TestData/<real file name> -- the SAME package-relative folder
            // appsettings.Development.json points a real local run at, resolved against THIS
            // assembly's own build output (TestData/ is CopyToOutputDirectory -- see
            // TestProjectEmitter), never the working directory a test happens to be run from.
            // Deliberately NOT a tool-synthesized fallback: there is one real production path
            // (appsettings.json's own SourceFileName, unchanged by the Development override) and
            // this harness names that exact file, so a source's own read test fails clearly
            // (FileNotFoundException) until its LOCAL-DATA fill actually supplies that file --
            // see EmitFileSourceTest/EmitExcelSourceTest's own doc comments for why those tests
            // are tagged [Trait("Category", "Integration")] rather than assumed to pass. A Flat
            // File Destination's own key (sinkFileKeys) points at _sinkOutputDirectory instead --
            // a real, writable, per-instance temp location, not a checked-in file -- so "Sink --
            // flat file" starter tests can write for real and read the result back with no
            // format-duplication risk. A File System Task's own source/destination connection-
            // manager keys (fileSystemTaskKeys) share that same directory, each with a distinct
            // ".fst.dat" suffix so a copy's source and destination never collide with a sink's
            // own ".out.txt" files or with each other. A ForEach Loop's own key (forEachLoopKeys)
            // points at its own dedicated SUBFOLDER (ForEachLoopFolder(key)) instead of a single
            // file, since this is the one shape that reads a FOLDER of files, not one file.
            lines.Add("        services.AddSingleton<IOptions<FileSourceOptions>>(Options.Create(new FileSourceOptions");
            lines.Add("        {");
            lines.Add("            Files =");
            lines.Add("            {");
            var sampleDataFallbackByKey = sampleDataFallbackFiles.ToDictionary(f => f.Key, f => f.FileName);
            foreach (var (key, fileName) in testDataFiles)
            {
                var realEntry = $"new FileSourceEntry {{ SourceFolder = Path.Combine(AppContext.BaseDirectory, \"TestData\"), SourceFileName = \"{fileName}\" }}";
                if (sampleDataFallbackByKey.TryGetValue(key, out var sampleFileName))
                {
                    var sampleEntry = $"new FileSourceEntry {{ SourceFolder = Path.Combine(AppContext.BaseDirectory, \"SampleData\"), SourceFileName = \"{sampleFileName}\" }}";
                    lines.Add($"                [\"{key}\"] = useSampleDataForFileSources ? {sampleEntry} : {realEntry},");
                }
                else
                {
                    // No Tier-A sample exists for this key (Excel) -- always the real file. Safe
                    // even under useSampleDataForFileSources=true: PackageClassEmitter.
                    // SupportsFakeHappyPath already excludes any Excel-sourced package from ever
                    // constructing the harness that way in the first place.
                    lines.Add($"                [\"{key}\"] = {realEntry},");
                }
            }
            foreach (var key in sinkFileKeys)
                lines.Add($"                [\"{key}\"] = new FileSourceEntry {{ SourceFolder = _sinkOutputDirectory, SourceFileName = \"{key}.out.txt\" }},");
            foreach (var key in fileSystemTaskKeys)
                lines.Add($"                [\"{key}\"] = new FileSourceEntry {{ SourceFolder = _sinkOutputDirectory, SourceFileName = \"{key}.fst.dat\" }},");
            foreach (var key in forEachLoopKeys)
                lines.Add($"                [\"{key}\"] = new FileSourceEntry {{ SourceFolder = ForEachLoopFolder(\"{key}\"), SourceFileName = \"\" }},");
            lines.Add("            },");
            lines.Add("        }));");
        }
        lines.AddRange(new List<string>
        {
            "        services.AddSingleton<IOptions<BulkCopyOptions>>(Options.Create(new BulkCopyOptions()));",
            "        services.AddSingleton<IPackageResultNotifier>(Notifier);",
            "        services.AddScoped<IUnitOfWork>(_ =>",
            "        {",
            "            var uow = new FakeUnitOfWork(NewDbContext()) { ThrowOnGetBindToken = ThrowOnGetBindToken };",
            "            CreatedUnitsOfWork.Add(uow);",
            "            return uow;",
            "        });",
            "",
            "        _root = services.BuildServiceProvider();",
            "    }",
            "",
            "    /// <summary>A fresh package instance, backed by this harness's own ServiceProvider --",
            "    /// calling RunAsync() resolves a NEW scoped IUnitOfWork/FakeUnitOfWork per DI scope,",
            $"    /// matching production wiring exactly (see {packageClassName}.RunAsync's own",
            "    /// `services.CreateAsyncScope()`).</summary>",
            $"    public {packageClassName} Package() => new(_root);",
            "",
            "    /// <summary>A standalone FakeUnitOfWork for a step-level test that calls one internal",
            "    /// method directly (e.g. `package.SQL_TruncateTargets(uow, ct)`) without ever going",
            "    /// through RunAsync -- not tracked in CreatedUnitsOfWork, since it was never resolved",
            "    /// from DI.</summary>",
            "    public FakeUnitOfWork NewUnitOfWork() => new(NewDbContext());",
            "",
            "    /// <summary>A REAL, already-begun UnitOfWork (not FakeUnitOfWork) -- only for a hand-run",
            "    /// [Trait(\"Category\", \"Integration\")] test against an actually reachable server (see",
            "    /// Tools/COPILOT_TESTING_GUIDE.md's own \"point this at a real server\" section: edit the",
            "    /// _databaseOptions line in this file's own constructor for a local run). A source that",
            "    /// takes IUnitOfWork -- an OLE DB/ADO NET Source's own SqlRowSource -- always attempts",
            "    /// sp_bindsession when given a non-null uow, and FakeUnitOfWork.GetBindTokenAsync always",
            "    /// returns the same literal placeholder string, which any real server correctly rejects;",
            "    /// only a genuine bind token (sp_getbindtoken, issued on THIS instance's own active",
            "    /// transaction) satisfies that call. Begun here, not left to the caller, because",
            "    /// production code never calls GetBindTokenAsync before BeginAsync either -- see",
            "    /// UnitOfWork's own precondition on that method. Never committed, so its own transaction",
            "    /// rolls back on disposal -- the caller owns disposal (`await using`), and a plain SELECT",
            "    /// read leaves nothing to roll back anyway.</summary>",
            $"    public async Task<UnitOfWork> NewRealUnitOfWorkAsync(CancellationToken ct = default)",
            "    {",
            $"        var options = new DbContextOptionsBuilder<{dbContextTypeName}>()",
            "            .UseSqlServer(SqlConnectionStringFactory.Build(_databaseOptions))",
            "            .Options;",
            $"        var uow = new UnitOfWork(new {dbContextTypeName}(options), new SqlBulkCopyFactory(), NullLogger<UnitOfWork>.Instance);",
            "        await uow.BeginAsync(IsolationLevel.ReadCommitted, ct);",
            "        return uow;",
            "    }",
            "",
            "    /// <summary>The real, resolved path a Flat File Destination method keyed by \"key\" writes",
            "    /// to -- the SAME path the generated File(key) helper resolves via FileSourceOptions,",
            "    /// computed here (not re-derived from a different formula) so a sink starter test can",
            "    /// read the real file back after WriteAsync returns.</summary>",
            "    public string SinkFilePath(string key) => Path.Combine(_sinkOutputDirectory, $\"{key}.out.txt\");",
            "",
            "    /// <summary>The real, resolved path a File System Task method keyed by \"key\" reads its",
            "    /// source from, or writes its destination to -- the SAME path the generated File(key)",
            "    /// helper resolves via FileSourceOptions. A starter test writes the source file here",
            "    /// before calling the method, then reads the destination file back from here",
            "    /// afterward.</summary>",
            "    public string FileSystemTaskPath(string key) => Path.Combine(_sinkOutputDirectory, $\"{key}.fst.dat\");",
            "",
            "    /// <summary>The real, writable folder a ForEach Loop method keyed by \"key\" enumerates --",
            "    /// the SAME folder the generated File(key) helper resolves via FileSourceOptions (a",
            "    /// folder-only entry, empty SourceFileName). A starter test writes its own source files",
            "    /// here before calling the method; created eagerly in the constructor (see above) since",
            "    /// Directory.EnumerateFiles throws if the folder does not exist yet.</summary>",
            "    public string ForEachLoopFolder(string key) => Path.Combine(_sinkOutputDirectory, key);",
            "",
            $"    private static {dbContextTypeName} NewDbContext()",
            "    {",
            $"        var options = new DbContextOptionsBuilder<{dbContextTypeName}>()",
            $"            .UseSqlServer(\"{fakeConnectionString}\")",
            "            .Options;",
            $"        return new {dbContextTypeName}(options);",
            "    }",
            "",
            "    public void Dispose()",
            "    {",
            "        _root.Dispose();",
            "        try { if (Directory.Exists(_sinkOutputDirectory)) Directory.Delete(_sinkOutputDirectory, recursive: true); }",
            "        catch (IOException) { /* best-effort cleanup, not a test failure */ }",
            "        catch (UnauthorizedAccessException) { }",
            "    }",
            "",
            "    private sealed class FixedTimeProvider(DateTimeOffset now) : TimeProvider",
            "    {",
            "        public override DateTimeOffset GetUtcNow() => now;",
            "    }",
            "}",
        });

        return Rendering.JoinLines(lines);
    }
}
